// flow-typed signature: 7bfbfc5d087874170ce6168caff5b66c
// flow-typed version: <<STUB>>/@types/chai-as-promised_v0.0.31/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chai-as-promised'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chai-as-promised' {
  declare module.exports: any;
}
