// flow-typed signature: 2d385d858292ff112ca939833ca04ee3
// flow-typed version: <<STUB>>/@types/chai_v4.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/chai' {
  declare module.exports: any;
}
