// flow-typed signature: f58456b38eae6df2434100d3a7881df1
// flow-typed version: <<STUB>>/@types/mocha_v^2.2.31/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/mocha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/mocha' {
  declare module.exports: any;
}
