// flow-typed signature: 2121f464db55a2a7cb7eb2b99d5b4708
// flow-typed version: <<STUB>>/@types/node_v8.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/node'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/node' {
  declare module.exports: any;
}
