// flow-typed signature: 59a0c8be7e676646e3e9be2f10a5c259
// flow-typed version: <<STUB>>/@types/promises-a-plus_v0.0.27/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/promises-a-plus'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/promises-a-plus' {
  declare module.exports: any;
}
