// flow-typed signature: c3724d10bbfe950c80d33cf06a6a1add
// flow-typed version: <<STUB>>/@types/sinon_v^2.1.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@types/sinon'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@types/sinon' {
  declare module.exports: any;
}
