// flow-typed signature: 47de5c8600a6d65b0baa7f00b949f3a7
// flow-typed version: <<STUB>>/apollo-link_v^0.0.3/flow_v0.50.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'apollo-link/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'apollo-link/dist/src/httpLink' {
  declare module.exports: any;
}

declare module 'apollo-link/dist/src/index' {
  declare module.exports: any;
}

declare module 'apollo-link/dist/src/link' {
  declare module.exports: any;
}

declare module 'apollo-link/dist/src/linkUtils' {
  declare module.exports: any;
}

declare module 'apollo-link/dist/src/pollingLink' {
  declare module.exports: any;
}

declare module 'apollo-link/dist/src/retryLink' {
  declare module.exports: any;
}

declare module 'apollo-link/dist/src/setContextLink' {
  declare module.exports: any;
}

declare module 'apollo-link/dist/src/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'apollo-link/coverage/lcov-report/prettify'>;
}
declare module 'apollo-link/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'apollo-link/coverage/lcov-report/sorter'>;
}
declare module 'apollo-link/dist/src/httpLink.js' {
  declare module.exports: $Exports<'apollo-link/dist/src/httpLink'>;
}
declare module 'apollo-link/dist/src/index.js' {
  declare module.exports: $Exports<'apollo-link/dist/src/index'>;
}
declare module 'apollo-link/dist/src/link.js' {
  declare module.exports: $Exports<'apollo-link/dist/src/link'>;
}
declare module 'apollo-link/dist/src/linkUtils.js' {
  declare module.exports: $Exports<'apollo-link/dist/src/linkUtils'>;
}
declare module 'apollo-link/dist/src/pollingLink.js' {
  declare module.exports: $Exports<'apollo-link/dist/src/pollingLink'>;
}
declare module 'apollo-link/dist/src/retryLink.js' {
  declare module.exports: $Exports<'apollo-link/dist/src/retryLink'>;
}
declare module 'apollo-link/dist/src/setContextLink.js' {
  declare module.exports: $Exports<'apollo-link/dist/src/setContextLink'>;
}
declare module 'apollo-link/dist/src/types.js' {
  declare module.exports: $Exports<'apollo-link/dist/src/types'>;
}
