// flow-typed signature: 0f2331ff719222925615171f332dd3b7
// flow-typed version: <<STUB>>/apollo-link-core_v^0.5.0/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-core/dist/src/index' {
  declare module.exports: any;
}

declare module 'apollo-link-core/dist/src/link' {
  declare module.exports: any;
}

declare module 'apollo-link-core/dist/src/linkUtils' {
  declare module.exports: any;
}

declare module 'apollo-link-core/dist/src/test-utils' {
  declare module.exports: any;
}

declare module 'apollo-link-core/dist/src/test-utils/mockLink' {
  declare module.exports: any;
}

declare module 'apollo-link-core/dist/src/test-utils/setContext' {
  declare module.exports: any;
}

declare module 'apollo-link-core/dist/src/test-utils/testingUtils' {
  declare module.exports: any;
}

declare module 'apollo-link-core/dist/src/types' {
  declare module.exports: any;
}

declare module 'apollo-link-core/dist/tests/link' {
  declare module.exports: any;
}

declare module 'apollo-link-core/dist/tests/linkUtils' {
  declare module.exports: any;
}

declare module 'apollo-link-core/dist/tests/tests' {
  declare module.exports: any;
}

declare module 'apollo-link-core/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-link-core/lib/link' {
  declare module.exports: any;
}

declare module 'apollo-link-core/lib/linkUtils' {
  declare module.exports: any;
}

declare module 'apollo-link-core/lib/test-utils' {
  declare module.exports: any;
}

declare module 'apollo-link-core/lib/test-utils/mockLink' {
  declare module.exports: any;
}

declare module 'apollo-link-core/lib/test-utils/setContext' {
  declare module.exports: any;
}

declare module 'apollo-link-core/lib/test-utils/testingUtils' {
  declare module.exports: any;
}

declare module 'apollo-link-core/lib/types' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-core/dist/src/index.js' {
  declare module.exports: $Exports<'apollo-link-core/dist/src/index'>;
}
declare module 'apollo-link-core/dist/src/link.js' {
  declare module.exports: $Exports<'apollo-link-core/dist/src/link'>;
}
declare module 'apollo-link-core/dist/src/linkUtils.js' {
  declare module.exports: $Exports<'apollo-link-core/dist/src/linkUtils'>;
}
declare module 'apollo-link-core/dist/src/test-utils.js' {
  declare module.exports: $Exports<'apollo-link-core/dist/src/test-utils'>;
}
declare module 'apollo-link-core/dist/src/test-utils/mockLink.js' {
  declare module.exports: $Exports<'apollo-link-core/dist/src/test-utils/mockLink'>;
}
declare module 'apollo-link-core/dist/src/test-utils/setContext.js' {
  declare module.exports: $Exports<'apollo-link-core/dist/src/test-utils/setContext'>;
}
declare module 'apollo-link-core/dist/src/test-utils/testingUtils.js' {
  declare module.exports: $Exports<'apollo-link-core/dist/src/test-utils/testingUtils'>;
}
declare module 'apollo-link-core/dist/src/types.js' {
  declare module.exports: $Exports<'apollo-link-core/dist/src/types'>;
}
declare module 'apollo-link-core/dist/tests/link.js' {
  declare module.exports: $Exports<'apollo-link-core/dist/tests/link'>;
}
declare module 'apollo-link-core/dist/tests/linkUtils.js' {
  declare module.exports: $Exports<'apollo-link-core/dist/tests/linkUtils'>;
}
declare module 'apollo-link-core/dist/tests/tests.js' {
  declare module.exports: $Exports<'apollo-link-core/dist/tests/tests'>;
}
declare module 'apollo-link-core/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-core/lib/index'>;
}
declare module 'apollo-link-core/lib/link.js' {
  declare module.exports: $Exports<'apollo-link-core/lib/link'>;
}
declare module 'apollo-link-core/lib/linkUtils.js' {
  declare module.exports: $Exports<'apollo-link-core/lib/linkUtils'>;
}
declare module 'apollo-link-core/lib/test-utils.js' {
  declare module.exports: $Exports<'apollo-link-core/lib/test-utils'>;
}
declare module 'apollo-link-core/lib/test-utils/mockLink.js' {
  declare module.exports: $Exports<'apollo-link-core/lib/test-utils/mockLink'>;
}
declare module 'apollo-link-core/lib/test-utils/setContext.js' {
  declare module.exports: $Exports<'apollo-link-core/lib/test-utils/setContext'>;
}
declare module 'apollo-link-core/lib/test-utils/testingUtils.js' {
  declare module.exports: $Exports<'apollo-link-core/lib/test-utils/testingUtils'>;
}
declare module 'apollo-link-core/lib/types.js' {
  declare module.exports: $Exports<'apollo-link-core/lib/types'>;
}
