// flow-typed signature: 5ed5f1460dfbfd7e51ac2acc8e6142dd
// flow-typed version: <<STUB>>/browserify_v^14.3.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'browserify'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'browserify' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'browserify/bin/args' {
  declare module.exports: any;
}

declare module 'browserify/bin/cmd' {
  declare module.exports: any;
}

declare module 'browserify/example/api/browser/bar' {
  declare module.exports: any;
}

declare module 'browserify/example/api/browser/foo' {
  declare module.exports: any;
}

declare module 'browserify/example/api/browser/main' {
  declare module.exports: any;
}

declare module 'browserify/example/api/build' {
  declare module.exports: any;
}

declare module 'browserify/example/multiple_bundles/beep' {
  declare module.exports: any;
}

declare module 'browserify/example/multiple_bundles/boop' {
  declare module.exports: any;
}

declare module 'browserify/example/multiple_bundles/robot' {
  declare module.exports: any;
}

declare module 'browserify/example/source_maps/build' {
  declare module.exports: any;
}

declare module 'browserify/example/source_maps/js/build/bundle' {
  declare module.exports: any;
}

declare module 'browserify/example/source_maps/js/foo' {
  declare module.exports: any;
}

declare module 'browserify/example/source_maps/js/main' {
  declare module.exports: any;
}

declare module 'browserify/example/source_maps/js/wunder/bar' {
  declare module.exports: any;
}

declare module 'browserify/lib/_empty' {
  declare module.exports: any;
}

declare module 'browserify/lib/builtins' {
  declare module.exports: any;
}

declare module 'browserify/test/args' {
  declare module.exports: any;
}

declare module 'browserify/test/array' {
  declare module.exports: any;
}

declare module 'browserify/test/array/one' {
  declare module.exports: any;
}

declare module 'browserify/test/array/three' {
  declare module.exports: any;
}

declare module 'browserify/test/array/two' {
  declare module.exports: any;
}

declare module 'browserify/test/async' {
  declare module.exports: any;
}

declare module 'browserify/test/async/src' {
  declare module.exports: any;
}

declare module 'browserify/test/backbone' {
  declare module.exports: any;
}

declare module 'browserify/test/bare_shebang' {
  declare module.exports: any;
}

declare module 'browserify/test/bare' {
  declare module.exports: any;
}

declare module 'browserify/test/bare/main' {
  declare module.exports: any;
}

declare module 'browserify/test/bin_entry' {
  declare module.exports: any;
}

declare module 'browserify/test/bin_tr_error' {
  declare module.exports: any;
}

declare module 'browserify/test/bin_tr_error/main' {
  declare module.exports: any;
}

declare module 'browserify/test/bin_tr_error/tr' {
  declare module.exports: any;
}

declare module 'browserify/test/bin' {
  declare module.exports: any;
}

declare module 'browserify/test/bom' {
  declare module.exports: any;
}

declare module 'browserify/test/bom/hello' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_file' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_file/wow' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/a/main' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/b/main' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/b/x' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/c/main' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/c/x' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/d/main' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/d/x' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/e/main' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/e/x' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/f/main' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/f/x' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/g/main' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/g/x' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/h/main' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/h/x' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/i/browser' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/i/main' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/i/x' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/j/browser' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/j/main' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/j/x' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/k/main' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/k/node_modules/x/hey' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/l/main' {
  declare module.exports: any;
}

declare module 'browserify/test/browser_field_resolve/l/node_modules/x/hey' {
  declare module.exports: any;
}

declare module 'browserify/test/buffer' {
  declare module.exports: any;
}

declare module 'browserify/test/bundle_external_global' {
  declare module.exports: any;
}

declare module 'browserify/test/bundle_external' {
  declare module.exports: any;
}

declare module 'browserify/test/bundle_external/boop' {
  declare module.exports: any;
}

declare module 'browserify/test/bundle_external/main' {
  declare module.exports: any;
}

declare module 'browserify/test/bundle_external/robot' {
  declare module.exports: any;
}

declare module 'browserify/test/bundle_sourcemap' {
  declare module.exports: any;
}

declare module 'browserify/test/bundle-bundle-external' {
  declare module.exports: any;
}

declare module 'browserify/test/bundle-bundle-external/bar' {
  declare module.exports: any;
}

declare module 'browserify/test/bundle-bundle-external/baz' {
  declare module.exports: any;
}

declare module 'browserify/test/bundle-bundle-external/foo' {
  declare module.exports: any;
}

declare module 'browserify/test/bundle-stream' {
  declare module.exports: any;
}

declare module 'browserify/test/bundle' {
  declare module.exports: any;
}

declare module 'browserify/test/catch' {
  declare module.exports: any;
}

declare module 'browserify/test/catch/main' {
  declare module.exports: any;
}

declare module 'browserify/test/circular' {
  declare module.exports: any;
}

declare module 'browserify/test/circular/a' {
  declare module.exports: any;
}

declare module 'browserify/test/circular/b' {
  declare module.exports: any;
}

declare module 'browserify/test/circular/main' {
  declare module.exports: any;
}

declare module 'browserify/test/coffee_bin' {
  declare module.exports: any;
}

declare module 'browserify/test/coffeeify' {
  declare module.exports: any;
}

declare module 'browserify/test/comment' {
  declare module.exports: any;
}

declare module 'browserify/test/comment/main' {
  declare module.exports: any;
}

declare module 'browserify/test/constants' {
  declare module.exports: any;
}

declare module 'browserify/test/crypto_ig' {
  declare module.exports: any;
}

declare module 'browserify/test/crypto' {
  declare module.exports: any;
}

declare module 'browserify/test/cycle' {
  declare module.exports: any;
}

declare module 'browserify/test/cycle/entry' {
  declare module.exports: any;
}

declare module 'browserify/test/cycle/mod1/a' {
  declare module.exports: any;
}

declare module 'browserify/test/cycle/mod1/b' {
  declare module.exports: any;
}

declare module 'browserify/test/cycle/mod2/a' {
  declare module.exports: any;
}

declare module 'browserify/test/cycle/mod2/b' {
  declare module.exports: any;
}

declare module 'browserify/test/debug_standalone' {
  declare module.exports: any;
}

declare module 'browserify/test/debug_standalone/x' {
  declare module.exports: any;
}

declare module 'browserify/test/dedupe-deps' {
  declare module.exports: any;
}

declare module 'browserify/test/dedupe-nomap' {
  declare module.exports: any;
}

declare module 'browserify/test/delay' {
  declare module.exports: any;
}

declare module 'browserify/test/delay/diverted' {
  declare module.exports: any;
}

declare module 'browserify/test/delay/main' {
  declare module.exports: any;
}

declare module 'browserify/test/dep' {
  declare module.exports: any;
}

declare module 'browserify/test/dollar' {
  declare module.exports: any;
}

declare module 'browserify/test/dollar/dollar/index' {
  declare module.exports: any;
}

declare module 'browserify/test/double_buffer' {
  declare module.exports: any;
}

declare module 'browserify/test/double_buffer/explicit' {
  declare module.exports: any;
}

declare module 'browserify/test/double_buffer/implicit' {
  declare module.exports: any;
}

declare module 'browserify/test/double_buffer/main' {
  declare module.exports: any;
}

declare module 'browserify/test/double_bundle_error' {
  declare module.exports: any;
}

declare module 'browserify/test/double_bundle_error/main' {
  declare module.exports: any;
}

declare module 'browserify/test/double_bundle_error/needs_three' {
  declare module.exports: any;
}

declare module 'browserify/test/double_bundle_error/one' {
  declare module.exports: any;
}

declare module 'browserify/test/double_bundle_error/three' {
  declare module.exports: any;
}

declare module 'browserify/test/double_bundle_error/two' {
  declare module.exports: any;
}

declare module 'browserify/test/double_bundle_json' {
  declare module.exports: any;
}

declare module 'browserify/test/double_bundle_json/index' {
  declare module.exports: any;
}

declare module 'browserify/test/double_bundle_parallel_cache' {
  declare module.exports: any;
}

declare module 'browserify/test/double_bundle_parallel' {
  declare module.exports: any;
}

declare module 'browserify/test/double_bundle' {
  declare module.exports: any;
}

declare module 'browserify/test/dup/foo-dup' {
  declare module.exports: any;
}

declare module 'browserify/test/dup/foo' {
  declare module.exports: any;
}

declare module 'browserify/test/dup/index' {
  declare module.exports: any;
}

declare module 'browserify/test/entry_exec' {
  declare module.exports: any;
}

declare module 'browserify/test/entry_exec/fail' {
  declare module.exports: any;
}

declare module 'browserify/test/entry_exec/main' {
  declare module.exports: any;
}

declare module 'browserify/test/entry_expose' {
  declare module.exports: any;
}

declare module 'browserify/test/entry_expose/main' {
  declare module.exports: any;
}

declare module 'browserify/test/entry_relative' {
  declare module.exports: any;
}

declare module 'browserify/test/entry' {
  declare module.exports: any;
}

declare module 'browserify/test/entry/main' {
  declare module.exports: any;
}

declare module 'browserify/test/entry/needs_three' {
  declare module.exports: any;
}

declare module 'browserify/test/entry/one' {
  declare module.exports: any;
}

declare module 'browserify/test/entry/three' {
  declare module.exports: any;
}

declare module 'browserify/test/entry/two' {
  declare module.exports: any;
}

declare module 'browserify/test/error_code' {
  declare module.exports: any;
}

declare module 'browserify/test/error_code/src' {
  declare module.exports: any;
}

declare module 'browserify/test/export' {
  declare module.exports: any;
}

declare module 'browserify/test/export/entry' {
  declare module.exports: any;
}

declare module 'browserify/test/external_args/main' {
  declare module.exports: any;
}

declare module 'browserify/test/external_shim' {
  declare module.exports: any;
}

declare module 'browserify/test/external_shim/bundle1' {
  declare module.exports: any;
}

declare module 'browserify/test/external_shim/bundle2' {
  declare module.exports: any;
}

declare module 'browserify/test/external_shim/shim' {
  declare module.exports: any;
}

declare module 'browserify/test/external' {
  declare module.exports: any;
}

declare module 'browserify/test/external/main' {
  declare module.exports: any;
}

declare module 'browserify/test/external/x' {
  declare module.exports: any;
}

declare module 'browserify/test/externalize' {
  declare module.exports: any;
}

declare module 'browserify/test/externalize/beep' {
  declare module.exports: any;
}

declare module 'browserify/test/externalize/boop' {
  declare module.exports: any;
}

declare module 'browserify/test/externalize/robot' {
  declare module.exports: any;
}

declare module 'browserify/test/fake' {
  declare module.exports: any;
}

declare module 'browserify/test/fake/fake_fs' {
  declare module.exports: any;
}

declare module 'browserify/test/fake/main' {
  declare module.exports: any;
}

declare module 'browserify/test/field' {
  declare module.exports: any;
}

declare module 'browserify/test/field/miss' {
  declare module.exports: any;
}

declare module 'browserify/test/field/node_modules/z-miss/browser' {
  declare module.exports: any;
}

declare module 'browserify/test/field/node_modules/z-miss/main' {
  declare module.exports: any;
}

declare module 'browserify/test/field/node_modules/z-object/browser' {
  declare module.exports: any;
}

declare module 'browserify/test/field/node_modules/z-object/main' {
  declare module.exports: any;
}

declare module 'browserify/test/field/node_modules/z-string/browser' {
  declare module.exports: any;
}

declare module 'browserify/test/field/node_modules/z-string/main' {
  declare module.exports: any;
}

declare module 'browserify/test/field/node_modules/z-sub/browser/a' {
  declare module.exports: any;
}

declare module 'browserify/test/field/node_modules/z-sub/browser/b' {
  declare module.exports: any;
}

declare module 'browserify/test/field/node_modules/z-sub/main' {
  declare module.exports: any;
}

declare module 'browserify/test/field/object' {
  declare module.exports: any;
}

declare module 'browserify/test/field/string' {
  declare module.exports: any;
}

declare module 'browserify/test/field/sub' {
  declare module.exports: any;
}

declare module 'browserify/test/file_event' {
  declare module.exports: any;
}

declare module 'browserify/test/five_bundle' {
  declare module.exports: any;
}

declare module 'browserify/test/full_paths' {
  declare module.exports: any;
}

declare module 'browserify/test/glob' {
  declare module.exports: any;
}

declare module 'browserify/test/glob/a' {
  declare module.exports: any;
}

declare module 'browserify/test/glob/b' {
  declare module.exports: any;
}

declare module 'browserify/test/glob/lib/z' {
  declare module.exports: any;
}

declare module 'browserify/test/glob/vendor/x' {
  declare module.exports: any;
}

declare module 'browserify/test/glob/vendor/y' {
  declare module.exports: any;
}

declare module 'browserify/test/global_coffeeify' {
  declare module.exports: any;
}

declare module 'browserify/test/global_noparse' {
  declare module.exports: any;
}

declare module 'browserify/test/global_recorder' {
  declare module.exports: any;
}

declare module 'browserify/test/global_recorder/main' {
  declare module.exports: any;
}

declare module 'browserify/test/global' {
  declare module.exports: any;
}

declare module 'browserify/test/global/buffer' {
  declare module.exports: any;
}

declare module 'browserify/test/global/filename' {
  declare module.exports: any;
}

declare module 'browserify/test/global/main' {
  declare module.exports: any;
}

declare module 'browserify/test/global/node_modules/aaa/index' {
  declare module.exports: any;
}

declare module 'browserify/test/global/node_modules/robot/index' {
  declare module.exports: any;
}

declare module 'browserify/test/global/node_modules/robot/lib/beep' {
  declare module.exports: any;
}

declare module 'browserify/test/global/tick' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/main' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/one/dir/f' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/one/dir/g' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/one/f' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/one/g' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/three/dir/f' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/three/dir/g' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/three/dir/h' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/three/f' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/three/g' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/three/h' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/two/dir/f' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/two/dir/g' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/two/dir/h' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/two/f' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/two/g' {
  declare module.exports: any;
}

declare module 'browserify/test/hash_instance_context/two/h' {
  declare module.exports: any;
}

declare module 'browserify/test/hash' {
  declare module.exports: any;
}

declare module 'browserify/test/hash/foo/other' {
  declare module.exports: any;
}

declare module 'browserify/test/hash/foo/two' {
  declare module.exports: any;
}

declare module 'browserify/test/hash/main' {
  declare module.exports: any;
}

declare module 'browserify/test/hash/one' {
  declare module.exports: any;
}

declare module 'browserify/test/hash/other' {
  declare module.exports: any;
}

declare module 'browserify/test/identical_different' {
  declare module.exports: any;
}

declare module 'browserify/test/identical_different/main' {
  declare module.exports: any;
}

declare module 'browserify/test/identical_different/node_modules/op/index' {
  declare module.exports: any;
}

declare module 'browserify/test/identical_different/wow/node_modules/op/index' {
  declare module.exports: any;
}

declare module 'browserify/test/identical_different/wow/y' {
  declare module.exports: any;
}

declare module 'browserify/test/identical_different/x' {
  declare module.exports: any;
}

declare module 'browserify/test/identical' {
  declare module.exports: any;
}

declare module 'browserify/test/identical/main' {
  declare module.exports: any;
}

declare module 'browserify/test/identical/x' {
  declare module.exports: any;
}

declare module 'browserify/test/identical/y' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore_browser_field' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore_browser_field/main' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore_browser_field/node_modules/a/browser' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore_browser_field/node_modules/a/main' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore_browser_field/node_modules/b/browser-x' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore_browser_field/node_modules/b/main' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore_browser_field/node_modules/b/x' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore_missing' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore_missing/main' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore_transform_key' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore_transform_key/main' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore_transform_key/node_modules/a/index' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore_transform_key/node_modules/evil-transform/index' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore/by-id' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore/by-relative' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore/double-skip' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore/double-skip/index' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore/double-skip/skip' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore/ignored/skip' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore/main' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore/relative/index' {
  declare module.exports: any;
}

declare module 'browserify/test/ignore/skip' {
  declare module.exports: any;
}

declare module 'browserify/test/json' {
  declare module.exports: any;
}

declare module 'browserify/test/json/evil' {
  declare module.exports: any;
}

declare module 'browserify/test/json/main' {
  declare module.exports: any;
}

declare module 'browserify/test/leak' {
  declare module.exports: any;
}

declare module 'browserify/test/maxlisteners' {
  declare module.exports: any;
}

declare module 'browserify/test/maxlisteners/main' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_bundle_unique' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_bundle' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_bundle/_prelude' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_bundle/a' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_bundle/b' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_bundle/c' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_entry_cross_require' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_entry_cross_require/a' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_entry_cross_require/c' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_entry_cross_require/lib/b' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_entry' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_entry/a' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_entry/b' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_entry/c' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_require' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_require/a' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_require/main' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_symlink' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_symlink/main' {
  declare module.exports: any;
}

declare module 'browserify/test/multi_symlink/x' {
  declare module.exports: any;
}

declare module 'browserify/test/no_builtins' {
  declare module.exports: any;
}

declare module 'browserify/test/no_builtins/extra/fs' {
  declare module.exports: any;
}

declare module 'browserify/test/no_builtins/extra/tls' {
  declare module.exports: any;
}

declare module 'browserify/test/no_builtins/main' {
  declare module.exports: any;
}

declare module 'browserify/test/node_modules/beep/index' {
  declare module.exports: any;
}

declare module 'browserify/test/node_modules/plugin-foo/index' {
  declare module.exports: any;
}

declare module 'browserify/test/node_modules/tr/index' {
  declare module.exports: any;
}

declare module 'browserify/test/noparse' {
  declare module.exports: any;
}

declare module 'browserify/test/noparse/a' {
  declare module.exports: any;
}

declare module 'browserify/test/noparse/b' {
  declare module.exports: any;
}

declare module 'browserify/test/noparse/dir1/1' {
  declare module.exports: any;
}

declare module 'browserify/test/noparse/dir1/dir2/2' {
  declare module.exports: any;
}

declare module 'browserify/test/noparse/node_modules/robot/lib/beep' {
  declare module.exports: any;
}

declare module 'browserify/test/noparse/node_modules/robot/lib/boop' {
  declare module.exports: any;
}

declare module 'browserify/test/noparse/node_modules/robot/main' {
  declare module.exports: any;
}

declare module 'browserify/test/pack' {
  declare module.exports: any;
}

declare module 'browserify/test/paths_transform' {
  declare module.exports: any;
}

declare module 'browserify/test/paths' {
  declare module.exports: any;
}

declare module 'browserify/test/paths/main' {
  declare module.exports: any;
}

declare module 'browserify/test/paths/x/aaa/index' {
  declare module.exports: any;
}

declare module 'browserify/test/paths/x/ccc/index' {
  declare module.exports: any;
}

declare module 'browserify/test/paths/y/bbb/index' {
  declare module.exports: any;
}

declare module 'browserify/test/paths/y/ccc/index' {
  declare module.exports: any;
}

declare module 'browserify/test/pipeline_deps' {
  declare module.exports: any;
}

declare module 'browserify/test/pipeline_deps/bar' {
  declare module.exports: any;
}

declare module 'browserify/test/pipeline_deps/foo' {
  declare module.exports: any;
}

declare module 'browserify/test/pipeline_deps/main' {
  declare module.exports: any;
}

declare module 'browserify/test/pipeline_deps/xyz' {
  declare module.exports: any;
}

declare module 'browserify/test/pkg_event' {
  declare module.exports: any;
}

declare module 'browserify/test/pkg_event/main' {
  declare module.exports: any;
}

declare module 'browserify/test/pkg' {
  declare module.exports: any;
}

declare module 'browserify/test/pkg/main' {
  declare module.exports: any;
}

declare module 'browserify/test/plugin' {
  declare module.exports: any;
}

declare module 'browserify/test/plugin/main' {
  declare module.exports: any;
}

declare module 'browserify/test/process' {
  declare module.exports: any;
}

declare module 'browserify/test/process/main' {
  declare module.exports: any;
}

declare module 'browserify/test/process/one' {
  declare module.exports: any;
}

declare module 'browserify/test/process/two' {
  declare module.exports: any;
}

declare module 'browserify/test/relative_dedupe' {
  declare module.exports: any;
}

declare module 'browserify/test/relative_dedupe/a/a' {
  declare module.exports: any;
}

declare module 'browserify/test/relative_dedupe/a/b' {
  declare module.exports: any;
}

declare module 'browserify/test/relative_dedupe/a/index' {
  declare module.exports: any;
}

declare module 'browserify/test/relative_dedupe/b/a' {
  declare module.exports: any;
}

declare module 'browserify/test/relative_dedupe/b/b' {
  declare module.exports: any;
}

declare module 'browserify/test/relative_dedupe/b/index' {
  declare module.exports: any;
}

declare module 'browserify/test/relative_dedupe/index' {
  declare module.exports: any;
}

declare module 'browserify/test/relative_dedupe/main' {
  declare module.exports: any;
}

declare module 'browserify/test/require_cache' {
  declare module.exports: any;
}

declare module 'browserify/test/require_expose' {
  declare module.exports: any;
}

declare module 'browserify/test/require_expose/main' {
  declare module.exports: any;
}

declare module 'browserify/test/require_expose/some_dep' {
  declare module.exports: any;
}

declare module 'browserify/test/reset' {
  declare module.exports: any;
}

declare module 'browserify/test/resolve_exposed' {
  declare module.exports: any;
}

declare module 'browserify/test/resolve_exposed/main' {
  declare module.exports: any;
}

declare module 'browserify/test/resolve_exposed/x' {
  declare module.exports: any;
}

declare module 'browserify/test/retarget' {
  declare module.exports: any;
}

declare module 'browserify/test/reverse_multi_bundle' {
  declare module.exports: any;
}

declare module 'browserify/test/reverse_multi_bundle/app' {
  declare module.exports: any;
}

declare module 'browserify/test/reverse_multi_bundle/arbitrary' {
  declare module.exports: any;
}

declare module 'browserify/test/reverse_multi_bundle/lazy' {
  declare module.exports: any;
}

declare module 'browserify/test/reverse_multi_bundle/shared' {
  declare module.exports: any;
}

declare module 'browserify/test/shared_symlink' {
  declare module.exports: any;
}

declare module 'browserify/test/shared_symlink/app/index' {
  declare module.exports: any;
}

declare module 'browserify/test/shared_symlink/app/node_modules/foo/index' {
  declare module.exports: any;
}

declare module 'browserify/test/shared_symlink/main' {
  declare module.exports: any;
}

declare module 'browserify/test/shared_symlink/shared/index' {
  declare module.exports: any;
}

declare module 'browserify/test/shebang' {
  declare module.exports: any;
}

declare module 'browserify/test/shebang/foo' {
  declare module.exports: any;
}

declare module 'browserify/test/shebang/main' {
  declare module.exports: any;
}

declare module 'browserify/test/standalone_events' {
  declare module.exports: any;
}

declare module 'browserify/test/standalone_sourcemap' {
  declare module.exports: any;
}

declare module 'browserify/test/standalone' {
  declare module.exports: any;
}

declare module 'browserify/test/standalone/main' {
  declare module.exports: any;
}

declare module 'browserify/test/standalone/one' {
  declare module.exports: any;
}

declare module 'browserify/test/standalone/two' {
  declare module.exports: any;
}

declare module 'browserify/test/stdin' {
  declare module.exports: any;
}

declare module 'browserify/test/stream_file' {
  declare module.exports: any;
}

declare module 'browserify/test/stream' {
  declare module.exports: any;
}

declare module 'browserify/test/stream/bar' {
  declare module.exports: any;
}

declare module 'browserify/test/stream/foo' {
  declare module.exports: any;
}

declare module 'browserify/test/stream/main' {
  declare module.exports: any;
}

declare module 'browserify/test/subdep' {
  declare module.exports: any;
}

declare module 'browserify/test/subdep/index' {
  declare module.exports: any;
}

declare module 'browserify/test/symlink_dedupe' {
  declare module.exports: any;
}

declare module 'browserify/test/symlink_dedupe/main' {
  declare module.exports: any;
}

declare module 'browserify/test/symlink_dedupe/one/f' {
  declare module.exports: any;
}

declare module 'browserify/test/symlink_dedupe/one/g' {
  declare module.exports: any;
}

declare module 'browserify/test/syntax_cache' {
  declare module.exports: any;
}

declare module 'browserify/test/syntax_cache/invalid' {
  declare module.exports: any;
}

declare module 'browserify/test/syntax_cache/valid' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_args' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_args/main' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_args/tr' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_error' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_flags' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_global' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_global/main' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_global/node_modules/tr/index' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_global/node_modules/x/index' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_global/node_modules/x/node_modules/tr/index' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_no_entry' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_no_entry/main' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_once' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_once/main' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_order' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_order/replace_aaa' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_order/replace_bbb' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_symlink' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_symlink/a-module/index' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_symlink/app/main' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_symlink/b-module/ext' {
  declare module.exports: any;
}

declare module 'browserify/test/tr_symlink/b-module/index' {
  declare module.exports: any;
}

declare module 'browserify/test/tr' {
  declare module.exports: any;
}

declare module 'browserify/test/tr/f' {
  declare module.exports: any;
}

declare module 'browserify/test/tr/main' {
  declare module.exports: any;
}

declare module 'browserify/test/tr/subdir/g' {
  declare module.exports: any;
}

declare module 'browserify/test/unicode' {
  declare module.exports: any;
}

declare module 'browserify/test/unicode/main' {
  declare module.exports: any;
}

declare module 'browserify/test/unicode/one' {
  declare module.exports: any;
}

declare module 'browserify/test/unicode/two' {
  declare module.exports: any;
}

declare module 'browserify/test/util' {
  declare module.exports: any;
}

declare module 'browserify/test/yield' {
  declare module.exports: any;
}

declare module 'browserify/test/yield/f' {
  declare module.exports: any;
}

declare module 'browserify/test/yield/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'browserify/bin/args.js' {
  declare module.exports: $Exports<'browserify/bin/args'>;
}
declare module 'browserify/bin/cmd.js' {
  declare module.exports: $Exports<'browserify/bin/cmd'>;
}
declare module 'browserify/example/api/browser/bar.js' {
  declare module.exports: $Exports<'browserify/example/api/browser/bar'>;
}
declare module 'browserify/example/api/browser/foo.js' {
  declare module.exports: $Exports<'browserify/example/api/browser/foo'>;
}
declare module 'browserify/example/api/browser/main.js' {
  declare module.exports: $Exports<'browserify/example/api/browser/main'>;
}
declare module 'browserify/example/api/build.js' {
  declare module.exports: $Exports<'browserify/example/api/build'>;
}
declare module 'browserify/example/multiple_bundles/beep.js' {
  declare module.exports: $Exports<'browserify/example/multiple_bundles/beep'>;
}
declare module 'browserify/example/multiple_bundles/boop.js' {
  declare module.exports: $Exports<'browserify/example/multiple_bundles/boop'>;
}
declare module 'browserify/example/multiple_bundles/robot.js' {
  declare module.exports: $Exports<'browserify/example/multiple_bundles/robot'>;
}
declare module 'browserify/example/source_maps/build.js' {
  declare module.exports: $Exports<'browserify/example/source_maps/build'>;
}
declare module 'browserify/example/source_maps/js/build/bundle.js' {
  declare module.exports: $Exports<'browserify/example/source_maps/js/build/bundle'>;
}
declare module 'browserify/example/source_maps/js/foo.js' {
  declare module.exports: $Exports<'browserify/example/source_maps/js/foo'>;
}
declare module 'browserify/example/source_maps/js/main.js' {
  declare module.exports: $Exports<'browserify/example/source_maps/js/main'>;
}
declare module 'browserify/example/source_maps/js/wunder/bar.js' {
  declare module.exports: $Exports<'browserify/example/source_maps/js/wunder/bar'>;
}
declare module 'browserify/index' {
  declare module.exports: $Exports<'browserify'>;
}
declare module 'browserify/index.js' {
  declare module.exports: $Exports<'browserify'>;
}
declare module 'browserify/lib/_empty.js' {
  declare module.exports: $Exports<'browserify/lib/_empty'>;
}
declare module 'browserify/lib/builtins.js' {
  declare module.exports: $Exports<'browserify/lib/builtins'>;
}
declare module 'browserify/test/args.js' {
  declare module.exports: $Exports<'browserify/test/args'>;
}
declare module 'browserify/test/array.js' {
  declare module.exports: $Exports<'browserify/test/array'>;
}
declare module 'browserify/test/array/one.js' {
  declare module.exports: $Exports<'browserify/test/array/one'>;
}
declare module 'browserify/test/array/three.js' {
  declare module.exports: $Exports<'browserify/test/array/three'>;
}
declare module 'browserify/test/array/two.js' {
  declare module.exports: $Exports<'browserify/test/array/two'>;
}
declare module 'browserify/test/async.js' {
  declare module.exports: $Exports<'browserify/test/async'>;
}
declare module 'browserify/test/async/src.js' {
  declare module.exports: $Exports<'browserify/test/async/src'>;
}
declare module 'browserify/test/backbone.js' {
  declare module.exports: $Exports<'browserify/test/backbone'>;
}
declare module 'browserify/test/bare_shebang.js' {
  declare module.exports: $Exports<'browserify/test/bare_shebang'>;
}
declare module 'browserify/test/bare.js' {
  declare module.exports: $Exports<'browserify/test/bare'>;
}
declare module 'browserify/test/bare/main.js' {
  declare module.exports: $Exports<'browserify/test/bare/main'>;
}
declare module 'browserify/test/bin_entry.js' {
  declare module.exports: $Exports<'browserify/test/bin_entry'>;
}
declare module 'browserify/test/bin_tr_error.js' {
  declare module.exports: $Exports<'browserify/test/bin_tr_error'>;
}
declare module 'browserify/test/bin_tr_error/main.js' {
  declare module.exports: $Exports<'browserify/test/bin_tr_error/main'>;
}
declare module 'browserify/test/bin_tr_error/tr.js' {
  declare module.exports: $Exports<'browserify/test/bin_tr_error/tr'>;
}
declare module 'browserify/test/bin.js' {
  declare module.exports: $Exports<'browserify/test/bin'>;
}
declare module 'browserify/test/bom.js' {
  declare module.exports: $Exports<'browserify/test/bom'>;
}
declare module 'browserify/test/bom/hello.js' {
  declare module.exports: $Exports<'browserify/test/bom/hello'>;
}
declare module 'browserify/test/browser_field_file.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_file'>;
}
declare module 'browserify/test/browser_field_file/wow.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_file/wow'>;
}
declare module 'browserify/test/browser_field_resolve.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve'>;
}
declare module 'browserify/test/browser_field_resolve/a/main.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/a/main'>;
}
declare module 'browserify/test/browser_field_resolve/b/main.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/b/main'>;
}
declare module 'browserify/test/browser_field_resolve/b/x.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/b/x'>;
}
declare module 'browserify/test/browser_field_resolve/c/main.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/c/main'>;
}
declare module 'browserify/test/browser_field_resolve/c/x.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/c/x'>;
}
declare module 'browserify/test/browser_field_resolve/d/main.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/d/main'>;
}
declare module 'browserify/test/browser_field_resolve/d/x.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/d/x'>;
}
declare module 'browserify/test/browser_field_resolve/e/main.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/e/main'>;
}
declare module 'browserify/test/browser_field_resolve/e/x.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/e/x'>;
}
declare module 'browserify/test/browser_field_resolve/f/main.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/f/main'>;
}
declare module 'browserify/test/browser_field_resolve/f/x.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/f/x'>;
}
declare module 'browserify/test/browser_field_resolve/g/main.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/g/main'>;
}
declare module 'browserify/test/browser_field_resolve/g/x.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/g/x'>;
}
declare module 'browserify/test/browser_field_resolve/h/main.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/h/main'>;
}
declare module 'browserify/test/browser_field_resolve/h/x.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/h/x'>;
}
declare module 'browserify/test/browser_field_resolve/i/browser.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/i/browser'>;
}
declare module 'browserify/test/browser_field_resolve/i/main.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/i/main'>;
}
declare module 'browserify/test/browser_field_resolve/i/x.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/i/x'>;
}
declare module 'browserify/test/browser_field_resolve/j/browser.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/j/browser'>;
}
declare module 'browserify/test/browser_field_resolve/j/main.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/j/main'>;
}
declare module 'browserify/test/browser_field_resolve/j/x.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/j/x'>;
}
declare module 'browserify/test/browser_field_resolve/k/main.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/k/main'>;
}
declare module 'browserify/test/browser_field_resolve/k/node_modules/x/hey.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/k/node_modules/x/hey'>;
}
declare module 'browserify/test/browser_field_resolve/l/main.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/l/main'>;
}
declare module 'browserify/test/browser_field_resolve/l/node_modules/x/hey.js' {
  declare module.exports: $Exports<'browserify/test/browser_field_resolve/l/node_modules/x/hey'>;
}
declare module 'browserify/test/buffer.js' {
  declare module.exports: $Exports<'browserify/test/buffer'>;
}
declare module 'browserify/test/bundle_external_global.js' {
  declare module.exports: $Exports<'browserify/test/bundle_external_global'>;
}
declare module 'browserify/test/bundle_external.js' {
  declare module.exports: $Exports<'browserify/test/bundle_external'>;
}
declare module 'browserify/test/bundle_external/boop.js' {
  declare module.exports: $Exports<'browserify/test/bundle_external/boop'>;
}
declare module 'browserify/test/bundle_external/main.js' {
  declare module.exports: $Exports<'browserify/test/bundle_external/main'>;
}
declare module 'browserify/test/bundle_external/robot.js' {
  declare module.exports: $Exports<'browserify/test/bundle_external/robot'>;
}
declare module 'browserify/test/bundle_sourcemap.js' {
  declare module.exports: $Exports<'browserify/test/bundle_sourcemap'>;
}
declare module 'browserify/test/bundle-bundle-external.js' {
  declare module.exports: $Exports<'browserify/test/bundle-bundle-external'>;
}
declare module 'browserify/test/bundle-bundle-external/bar.js' {
  declare module.exports: $Exports<'browserify/test/bundle-bundle-external/bar'>;
}
declare module 'browserify/test/bundle-bundle-external/baz.js' {
  declare module.exports: $Exports<'browserify/test/bundle-bundle-external/baz'>;
}
declare module 'browserify/test/bundle-bundle-external/foo.js' {
  declare module.exports: $Exports<'browserify/test/bundle-bundle-external/foo'>;
}
declare module 'browserify/test/bundle-stream.js' {
  declare module.exports: $Exports<'browserify/test/bundle-stream'>;
}
declare module 'browserify/test/bundle.js' {
  declare module.exports: $Exports<'browserify/test/bundle'>;
}
declare module 'browserify/test/catch.js' {
  declare module.exports: $Exports<'browserify/test/catch'>;
}
declare module 'browserify/test/catch/main.js' {
  declare module.exports: $Exports<'browserify/test/catch/main'>;
}
declare module 'browserify/test/circular.js' {
  declare module.exports: $Exports<'browserify/test/circular'>;
}
declare module 'browserify/test/circular/a.js' {
  declare module.exports: $Exports<'browserify/test/circular/a'>;
}
declare module 'browserify/test/circular/b.js' {
  declare module.exports: $Exports<'browserify/test/circular/b'>;
}
declare module 'browserify/test/circular/main.js' {
  declare module.exports: $Exports<'browserify/test/circular/main'>;
}
declare module 'browserify/test/coffee_bin.js' {
  declare module.exports: $Exports<'browserify/test/coffee_bin'>;
}
declare module 'browserify/test/coffeeify.js' {
  declare module.exports: $Exports<'browserify/test/coffeeify'>;
}
declare module 'browserify/test/comment.js' {
  declare module.exports: $Exports<'browserify/test/comment'>;
}
declare module 'browserify/test/comment/main.js' {
  declare module.exports: $Exports<'browserify/test/comment/main'>;
}
declare module 'browserify/test/constants.js' {
  declare module.exports: $Exports<'browserify/test/constants'>;
}
declare module 'browserify/test/crypto_ig.js' {
  declare module.exports: $Exports<'browserify/test/crypto_ig'>;
}
declare module 'browserify/test/crypto.js' {
  declare module.exports: $Exports<'browserify/test/crypto'>;
}
declare module 'browserify/test/cycle.js' {
  declare module.exports: $Exports<'browserify/test/cycle'>;
}
declare module 'browserify/test/cycle/entry.js' {
  declare module.exports: $Exports<'browserify/test/cycle/entry'>;
}
declare module 'browserify/test/cycle/mod1/a.js' {
  declare module.exports: $Exports<'browserify/test/cycle/mod1/a'>;
}
declare module 'browserify/test/cycle/mod1/b.js' {
  declare module.exports: $Exports<'browserify/test/cycle/mod1/b'>;
}
declare module 'browserify/test/cycle/mod2/a.js' {
  declare module.exports: $Exports<'browserify/test/cycle/mod2/a'>;
}
declare module 'browserify/test/cycle/mod2/b.js' {
  declare module.exports: $Exports<'browserify/test/cycle/mod2/b'>;
}
declare module 'browserify/test/debug_standalone.js' {
  declare module.exports: $Exports<'browserify/test/debug_standalone'>;
}
declare module 'browserify/test/debug_standalone/x.js' {
  declare module.exports: $Exports<'browserify/test/debug_standalone/x'>;
}
declare module 'browserify/test/dedupe-deps.js' {
  declare module.exports: $Exports<'browserify/test/dedupe-deps'>;
}
declare module 'browserify/test/dedupe-nomap.js' {
  declare module.exports: $Exports<'browserify/test/dedupe-nomap'>;
}
declare module 'browserify/test/delay.js' {
  declare module.exports: $Exports<'browserify/test/delay'>;
}
declare module 'browserify/test/delay/diverted.js' {
  declare module.exports: $Exports<'browserify/test/delay/diverted'>;
}
declare module 'browserify/test/delay/main.js' {
  declare module.exports: $Exports<'browserify/test/delay/main'>;
}
declare module 'browserify/test/dep.js' {
  declare module.exports: $Exports<'browserify/test/dep'>;
}
declare module 'browserify/test/dollar.js' {
  declare module.exports: $Exports<'browserify/test/dollar'>;
}
declare module 'browserify/test/dollar/dollar/index.js' {
  declare module.exports: $Exports<'browserify/test/dollar/dollar/index'>;
}
declare module 'browserify/test/double_buffer.js' {
  declare module.exports: $Exports<'browserify/test/double_buffer'>;
}
declare module 'browserify/test/double_buffer/explicit.js' {
  declare module.exports: $Exports<'browserify/test/double_buffer/explicit'>;
}
declare module 'browserify/test/double_buffer/implicit.js' {
  declare module.exports: $Exports<'browserify/test/double_buffer/implicit'>;
}
declare module 'browserify/test/double_buffer/main.js' {
  declare module.exports: $Exports<'browserify/test/double_buffer/main'>;
}
declare module 'browserify/test/double_bundle_error.js' {
  declare module.exports: $Exports<'browserify/test/double_bundle_error'>;
}
declare module 'browserify/test/double_bundle_error/main.js' {
  declare module.exports: $Exports<'browserify/test/double_bundle_error/main'>;
}
declare module 'browserify/test/double_bundle_error/needs_three.js' {
  declare module.exports: $Exports<'browserify/test/double_bundle_error/needs_three'>;
}
declare module 'browserify/test/double_bundle_error/one.js' {
  declare module.exports: $Exports<'browserify/test/double_bundle_error/one'>;
}
declare module 'browserify/test/double_bundle_error/three.js' {
  declare module.exports: $Exports<'browserify/test/double_bundle_error/three'>;
}
declare module 'browserify/test/double_bundle_error/two.js' {
  declare module.exports: $Exports<'browserify/test/double_bundle_error/two'>;
}
declare module 'browserify/test/double_bundle_json.js' {
  declare module.exports: $Exports<'browserify/test/double_bundle_json'>;
}
declare module 'browserify/test/double_bundle_json/index.js' {
  declare module.exports: $Exports<'browserify/test/double_bundle_json/index'>;
}
declare module 'browserify/test/double_bundle_parallel_cache.js' {
  declare module.exports: $Exports<'browserify/test/double_bundle_parallel_cache'>;
}
declare module 'browserify/test/double_bundle_parallel.js' {
  declare module.exports: $Exports<'browserify/test/double_bundle_parallel'>;
}
declare module 'browserify/test/double_bundle.js' {
  declare module.exports: $Exports<'browserify/test/double_bundle'>;
}
declare module 'browserify/test/dup/foo-dup.js' {
  declare module.exports: $Exports<'browserify/test/dup/foo-dup'>;
}
declare module 'browserify/test/dup/foo.js' {
  declare module.exports: $Exports<'browserify/test/dup/foo'>;
}
declare module 'browserify/test/dup/index.js' {
  declare module.exports: $Exports<'browserify/test/dup/index'>;
}
declare module 'browserify/test/entry_exec.js' {
  declare module.exports: $Exports<'browserify/test/entry_exec'>;
}
declare module 'browserify/test/entry_exec/fail.js' {
  declare module.exports: $Exports<'browserify/test/entry_exec/fail'>;
}
declare module 'browserify/test/entry_exec/main.js' {
  declare module.exports: $Exports<'browserify/test/entry_exec/main'>;
}
declare module 'browserify/test/entry_expose.js' {
  declare module.exports: $Exports<'browserify/test/entry_expose'>;
}
declare module 'browserify/test/entry_expose/main.js' {
  declare module.exports: $Exports<'browserify/test/entry_expose/main'>;
}
declare module 'browserify/test/entry_relative.js' {
  declare module.exports: $Exports<'browserify/test/entry_relative'>;
}
declare module 'browserify/test/entry.js' {
  declare module.exports: $Exports<'browserify/test/entry'>;
}
declare module 'browserify/test/entry/main.js' {
  declare module.exports: $Exports<'browserify/test/entry/main'>;
}
declare module 'browserify/test/entry/needs_three.js' {
  declare module.exports: $Exports<'browserify/test/entry/needs_three'>;
}
declare module 'browserify/test/entry/one.js' {
  declare module.exports: $Exports<'browserify/test/entry/one'>;
}
declare module 'browserify/test/entry/three.js' {
  declare module.exports: $Exports<'browserify/test/entry/three'>;
}
declare module 'browserify/test/entry/two.js' {
  declare module.exports: $Exports<'browserify/test/entry/two'>;
}
declare module 'browserify/test/error_code.js' {
  declare module.exports: $Exports<'browserify/test/error_code'>;
}
declare module 'browserify/test/error_code/src.js' {
  declare module.exports: $Exports<'browserify/test/error_code/src'>;
}
declare module 'browserify/test/export.js' {
  declare module.exports: $Exports<'browserify/test/export'>;
}
declare module 'browserify/test/export/entry.js' {
  declare module.exports: $Exports<'browserify/test/export/entry'>;
}
declare module 'browserify/test/external_args/main.js' {
  declare module.exports: $Exports<'browserify/test/external_args/main'>;
}
declare module 'browserify/test/external_shim.js' {
  declare module.exports: $Exports<'browserify/test/external_shim'>;
}
declare module 'browserify/test/external_shim/bundle1.js' {
  declare module.exports: $Exports<'browserify/test/external_shim/bundle1'>;
}
declare module 'browserify/test/external_shim/bundle2.js' {
  declare module.exports: $Exports<'browserify/test/external_shim/bundle2'>;
}
declare module 'browserify/test/external_shim/shim.js' {
  declare module.exports: $Exports<'browserify/test/external_shim/shim'>;
}
declare module 'browserify/test/external.js' {
  declare module.exports: $Exports<'browserify/test/external'>;
}
declare module 'browserify/test/external/main.js' {
  declare module.exports: $Exports<'browserify/test/external/main'>;
}
declare module 'browserify/test/external/x.js' {
  declare module.exports: $Exports<'browserify/test/external/x'>;
}
declare module 'browserify/test/externalize.js' {
  declare module.exports: $Exports<'browserify/test/externalize'>;
}
declare module 'browserify/test/externalize/beep.js' {
  declare module.exports: $Exports<'browserify/test/externalize/beep'>;
}
declare module 'browserify/test/externalize/boop.js' {
  declare module.exports: $Exports<'browserify/test/externalize/boop'>;
}
declare module 'browserify/test/externalize/robot.js' {
  declare module.exports: $Exports<'browserify/test/externalize/robot'>;
}
declare module 'browserify/test/fake.js' {
  declare module.exports: $Exports<'browserify/test/fake'>;
}
declare module 'browserify/test/fake/fake_fs.js' {
  declare module.exports: $Exports<'browserify/test/fake/fake_fs'>;
}
declare module 'browserify/test/fake/main.js' {
  declare module.exports: $Exports<'browserify/test/fake/main'>;
}
declare module 'browserify/test/field.js' {
  declare module.exports: $Exports<'browserify/test/field'>;
}
declare module 'browserify/test/field/miss.js' {
  declare module.exports: $Exports<'browserify/test/field/miss'>;
}
declare module 'browserify/test/field/node_modules/z-miss/browser.js' {
  declare module.exports: $Exports<'browserify/test/field/node_modules/z-miss/browser'>;
}
declare module 'browserify/test/field/node_modules/z-miss/main.js' {
  declare module.exports: $Exports<'browserify/test/field/node_modules/z-miss/main'>;
}
declare module 'browserify/test/field/node_modules/z-object/browser.js' {
  declare module.exports: $Exports<'browserify/test/field/node_modules/z-object/browser'>;
}
declare module 'browserify/test/field/node_modules/z-object/main.js' {
  declare module.exports: $Exports<'browserify/test/field/node_modules/z-object/main'>;
}
declare module 'browserify/test/field/node_modules/z-string/browser.js' {
  declare module.exports: $Exports<'browserify/test/field/node_modules/z-string/browser'>;
}
declare module 'browserify/test/field/node_modules/z-string/main.js' {
  declare module.exports: $Exports<'browserify/test/field/node_modules/z-string/main'>;
}
declare module 'browserify/test/field/node_modules/z-sub/browser/a.js' {
  declare module.exports: $Exports<'browserify/test/field/node_modules/z-sub/browser/a'>;
}
declare module 'browserify/test/field/node_modules/z-sub/browser/b.js' {
  declare module.exports: $Exports<'browserify/test/field/node_modules/z-sub/browser/b'>;
}
declare module 'browserify/test/field/node_modules/z-sub/main.js' {
  declare module.exports: $Exports<'browserify/test/field/node_modules/z-sub/main'>;
}
declare module 'browserify/test/field/object.js' {
  declare module.exports: $Exports<'browserify/test/field/object'>;
}
declare module 'browserify/test/field/string.js' {
  declare module.exports: $Exports<'browserify/test/field/string'>;
}
declare module 'browserify/test/field/sub.js' {
  declare module.exports: $Exports<'browserify/test/field/sub'>;
}
declare module 'browserify/test/file_event.js' {
  declare module.exports: $Exports<'browserify/test/file_event'>;
}
declare module 'browserify/test/five_bundle.js' {
  declare module.exports: $Exports<'browserify/test/five_bundle'>;
}
declare module 'browserify/test/full_paths.js' {
  declare module.exports: $Exports<'browserify/test/full_paths'>;
}
declare module 'browserify/test/glob.js' {
  declare module.exports: $Exports<'browserify/test/glob'>;
}
declare module 'browserify/test/glob/a.js' {
  declare module.exports: $Exports<'browserify/test/glob/a'>;
}
declare module 'browserify/test/glob/b.js' {
  declare module.exports: $Exports<'browserify/test/glob/b'>;
}
declare module 'browserify/test/glob/lib/z.js' {
  declare module.exports: $Exports<'browserify/test/glob/lib/z'>;
}
declare module 'browserify/test/glob/vendor/x.js' {
  declare module.exports: $Exports<'browserify/test/glob/vendor/x'>;
}
declare module 'browserify/test/glob/vendor/y.js' {
  declare module.exports: $Exports<'browserify/test/glob/vendor/y'>;
}
declare module 'browserify/test/global_coffeeify.js' {
  declare module.exports: $Exports<'browserify/test/global_coffeeify'>;
}
declare module 'browserify/test/global_noparse.js' {
  declare module.exports: $Exports<'browserify/test/global_noparse'>;
}
declare module 'browserify/test/global_recorder.js' {
  declare module.exports: $Exports<'browserify/test/global_recorder'>;
}
declare module 'browserify/test/global_recorder/main.js' {
  declare module.exports: $Exports<'browserify/test/global_recorder/main'>;
}
declare module 'browserify/test/global.js' {
  declare module.exports: $Exports<'browserify/test/global'>;
}
declare module 'browserify/test/global/buffer.js' {
  declare module.exports: $Exports<'browserify/test/global/buffer'>;
}
declare module 'browserify/test/global/filename.js' {
  declare module.exports: $Exports<'browserify/test/global/filename'>;
}
declare module 'browserify/test/global/main.js' {
  declare module.exports: $Exports<'browserify/test/global/main'>;
}
declare module 'browserify/test/global/node_modules/aaa/index.js' {
  declare module.exports: $Exports<'browserify/test/global/node_modules/aaa/index'>;
}
declare module 'browserify/test/global/node_modules/robot/index.js' {
  declare module.exports: $Exports<'browserify/test/global/node_modules/robot/index'>;
}
declare module 'browserify/test/global/node_modules/robot/lib/beep.js' {
  declare module.exports: $Exports<'browserify/test/global/node_modules/robot/lib/beep'>;
}
declare module 'browserify/test/global/tick.js' {
  declare module.exports: $Exports<'browserify/test/global/tick'>;
}
declare module 'browserify/test/hash_instance_context.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context'>;
}
declare module 'browserify/test/hash_instance_context/main.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/main'>;
}
declare module 'browserify/test/hash_instance_context/one/dir/f.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/one/dir/f'>;
}
declare module 'browserify/test/hash_instance_context/one/dir/g.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/one/dir/g'>;
}
declare module 'browserify/test/hash_instance_context/one/f.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/one/f'>;
}
declare module 'browserify/test/hash_instance_context/one/g.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/one/g'>;
}
declare module 'browserify/test/hash_instance_context/three/dir/f.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/three/dir/f'>;
}
declare module 'browserify/test/hash_instance_context/three/dir/g.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/three/dir/g'>;
}
declare module 'browserify/test/hash_instance_context/three/dir/h.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/three/dir/h'>;
}
declare module 'browserify/test/hash_instance_context/three/f.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/three/f'>;
}
declare module 'browserify/test/hash_instance_context/three/g.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/three/g'>;
}
declare module 'browserify/test/hash_instance_context/three/h.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/three/h'>;
}
declare module 'browserify/test/hash_instance_context/two/dir/f.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/two/dir/f'>;
}
declare module 'browserify/test/hash_instance_context/two/dir/g.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/two/dir/g'>;
}
declare module 'browserify/test/hash_instance_context/two/dir/h.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/two/dir/h'>;
}
declare module 'browserify/test/hash_instance_context/two/f.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/two/f'>;
}
declare module 'browserify/test/hash_instance_context/two/g.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/two/g'>;
}
declare module 'browserify/test/hash_instance_context/two/h.js' {
  declare module.exports: $Exports<'browserify/test/hash_instance_context/two/h'>;
}
declare module 'browserify/test/hash.js' {
  declare module.exports: $Exports<'browserify/test/hash'>;
}
declare module 'browserify/test/hash/foo/other.js' {
  declare module.exports: $Exports<'browserify/test/hash/foo/other'>;
}
declare module 'browserify/test/hash/foo/two.js' {
  declare module.exports: $Exports<'browserify/test/hash/foo/two'>;
}
declare module 'browserify/test/hash/main.js' {
  declare module.exports: $Exports<'browserify/test/hash/main'>;
}
declare module 'browserify/test/hash/one.js' {
  declare module.exports: $Exports<'browserify/test/hash/one'>;
}
declare module 'browserify/test/hash/other.js' {
  declare module.exports: $Exports<'browserify/test/hash/other'>;
}
declare module 'browserify/test/identical_different.js' {
  declare module.exports: $Exports<'browserify/test/identical_different'>;
}
declare module 'browserify/test/identical_different/main.js' {
  declare module.exports: $Exports<'browserify/test/identical_different/main'>;
}
declare module 'browserify/test/identical_different/node_modules/op/index.js' {
  declare module.exports: $Exports<'browserify/test/identical_different/node_modules/op/index'>;
}
declare module 'browserify/test/identical_different/wow/node_modules/op/index.js' {
  declare module.exports: $Exports<'browserify/test/identical_different/wow/node_modules/op/index'>;
}
declare module 'browserify/test/identical_different/wow/y.js' {
  declare module.exports: $Exports<'browserify/test/identical_different/wow/y'>;
}
declare module 'browserify/test/identical_different/x.js' {
  declare module.exports: $Exports<'browserify/test/identical_different/x'>;
}
declare module 'browserify/test/identical.js' {
  declare module.exports: $Exports<'browserify/test/identical'>;
}
declare module 'browserify/test/identical/main.js' {
  declare module.exports: $Exports<'browserify/test/identical/main'>;
}
declare module 'browserify/test/identical/x.js' {
  declare module.exports: $Exports<'browserify/test/identical/x'>;
}
declare module 'browserify/test/identical/y.js' {
  declare module.exports: $Exports<'browserify/test/identical/y'>;
}
declare module 'browserify/test/ignore_browser_field.js' {
  declare module.exports: $Exports<'browserify/test/ignore_browser_field'>;
}
declare module 'browserify/test/ignore_browser_field/main.js' {
  declare module.exports: $Exports<'browserify/test/ignore_browser_field/main'>;
}
declare module 'browserify/test/ignore_browser_field/node_modules/a/browser.js' {
  declare module.exports: $Exports<'browserify/test/ignore_browser_field/node_modules/a/browser'>;
}
declare module 'browserify/test/ignore_browser_field/node_modules/a/main.js' {
  declare module.exports: $Exports<'browserify/test/ignore_browser_field/node_modules/a/main'>;
}
declare module 'browserify/test/ignore_browser_field/node_modules/b/browser-x.js' {
  declare module.exports: $Exports<'browserify/test/ignore_browser_field/node_modules/b/browser-x'>;
}
declare module 'browserify/test/ignore_browser_field/node_modules/b/main.js' {
  declare module.exports: $Exports<'browserify/test/ignore_browser_field/node_modules/b/main'>;
}
declare module 'browserify/test/ignore_browser_field/node_modules/b/x.js' {
  declare module.exports: $Exports<'browserify/test/ignore_browser_field/node_modules/b/x'>;
}
declare module 'browserify/test/ignore_missing.js' {
  declare module.exports: $Exports<'browserify/test/ignore_missing'>;
}
declare module 'browserify/test/ignore_missing/main.js' {
  declare module.exports: $Exports<'browserify/test/ignore_missing/main'>;
}
declare module 'browserify/test/ignore_transform_key.js' {
  declare module.exports: $Exports<'browserify/test/ignore_transform_key'>;
}
declare module 'browserify/test/ignore_transform_key/main.js' {
  declare module.exports: $Exports<'browserify/test/ignore_transform_key/main'>;
}
declare module 'browserify/test/ignore_transform_key/node_modules/a/index.js' {
  declare module.exports: $Exports<'browserify/test/ignore_transform_key/node_modules/a/index'>;
}
declare module 'browserify/test/ignore_transform_key/node_modules/evil-transform/index.js' {
  declare module.exports: $Exports<'browserify/test/ignore_transform_key/node_modules/evil-transform/index'>;
}
declare module 'browserify/test/ignore.js' {
  declare module.exports: $Exports<'browserify/test/ignore'>;
}
declare module 'browserify/test/ignore/by-id.js' {
  declare module.exports: $Exports<'browserify/test/ignore/by-id'>;
}
declare module 'browserify/test/ignore/by-relative.js' {
  declare module.exports: $Exports<'browserify/test/ignore/by-relative'>;
}
declare module 'browserify/test/ignore/double-skip.js' {
  declare module.exports: $Exports<'browserify/test/ignore/double-skip'>;
}
declare module 'browserify/test/ignore/double-skip/index.js' {
  declare module.exports: $Exports<'browserify/test/ignore/double-skip/index'>;
}
declare module 'browserify/test/ignore/double-skip/skip.js' {
  declare module.exports: $Exports<'browserify/test/ignore/double-skip/skip'>;
}
declare module 'browserify/test/ignore/ignored/skip.js' {
  declare module.exports: $Exports<'browserify/test/ignore/ignored/skip'>;
}
declare module 'browserify/test/ignore/main.js' {
  declare module.exports: $Exports<'browserify/test/ignore/main'>;
}
declare module 'browserify/test/ignore/relative/index.js' {
  declare module.exports: $Exports<'browserify/test/ignore/relative/index'>;
}
declare module 'browserify/test/ignore/skip.js' {
  declare module.exports: $Exports<'browserify/test/ignore/skip'>;
}
declare module 'browserify/test/json.js' {
  declare module.exports: $Exports<'browserify/test/json'>;
}
declare module 'browserify/test/json/evil.js' {
  declare module.exports: $Exports<'browserify/test/json/evil'>;
}
declare module 'browserify/test/json/main.js' {
  declare module.exports: $Exports<'browserify/test/json/main'>;
}
declare module 'browserify/test/leak.js' {
  declare module.exports: $Exports<'browserify/test/leak'>;
}
declare module 'browserify/test/maxlisteners.js' {
  declare module.exports: $Exports<'browserify/test/maxlisteners'>;
}
declare module 'browserify/test/maxlisteners/main.js' {
  declare module.exports: $Exports<'browserify/test/maxlisteners/main'>;
}
declare module 'browserify/test/multi_bundle_unique.js' {
  declare module.exports: $Exports<'browserify/test/multi_bundle_unique'>;
}
declare module 'browserify/test/multi_bundle.js' {
  declare module.exports: $Exports<'browserify/test/multi_bundle'>;
}
declare module 'browserify/test/multi_bundle/_prelude.js' {
  declare module.exports: $Exports<'browserify/test/multi_bundle/_prelude'>;
}
declare module 'browserify/test/multi_bundle/a.js' {
  declare module.exports: $Exports<'browserify/test/multi_bundle/a'>;
}
declare module 'browserify/test/multi_bundle/b.js' {
  declare module.exports: $Exports<'browserify/test/multi_bundle/b'>;
}
declare module 'browserify/test/multi_bundle/c.js' {
  declare module.exports: $Exports<'browserify/test/multi_bundle/c'>;
}
declare module 'browserify/test/multi_entry_cross_require.js' {
  declare module.exports: $Exports<'browserify/test/multi_entry_cross_require'>;
}
declare module 'browserify/test/multi_entry_cross_require/a.js' {
  declare module.exports: $Exports<'browserify/test/multi_entry_cross_require/a'>;
}
declare module 'browserify/test/multi_entry_cross_require/c.js' {
  declare module.exports: $Exports<'browserify/test/multi_entry_cross_require/c'>;
}
declare module 'browserify/test/multi_entry_cross_require/lib/b.js' {
  declare module.exports: $Exports<'browserify/test/multi_entry_cross_require/lib/b'>;
}
declare module 'browserify/test/multi_entry.js' {
  declare module.exports: $Exports<'browserify/test/multi_entry'>;
}
declare module 'browserify/test/multi_entry/a.js' {
  declare module.exports: $Exports<'browserify/test/multi_entry/a'>;
}
declare module 'browserify/test/multi_entry/b.js' {
  declare module.exports: $Exports<'browserify/test/multi_entry/b'>;
}
declare module 'browserify/test/multi_entry/c.js' {
  declare module.exports: $Exports<'browserify/test/multi_entry/c'>;
}
declare module 'browserify/test/multi_require.js' {
  declare module.exports: $Exports<'browserify/test/multi_require'>;
}
declare module 'browserify/test/multi_require/a.js' {
  declare module.exports: $Exports<'browserify/test/multi_require/a'>;
}
declare module 'browserify/test/multi_require/main.js' {
  declare module.exports: $Exports<'browserify/test/multi_require/main'>;
}
declare module 'browserify/test/multi_symlink.js' {
  declare module.exports: $Exports<'browserify/test/multi_symlink'>;
}
declare module 'browserify/test/multi_symlink/main.js' {
  declare module.exports: $Exports<'browserify/test/multi_symlink/main'>;
}
declare module 'browserify/test/multi_symlink/x.js' {
  declare module.exports: $Exports<'browserify/test/multi_symlink/x'>;
}
declare module 'browserify/test/no_builtins.js' {
  declare module.exports: $Exports<'browserify/test/no_builtins'>;
}
declare module 'browserify/test/no_builtins/extra/fs.js' {
  declare module.exports: $Exports<'browserify/test/no_builtins/extra/fs'>;
}
declare module 'browserify/test/no_builtins/extra/tls.js' {
  declare module.exports: $Exports<'browserify/test/no_builtins/extra/tls'>;
}
declare module 'browserify/test/no_builtins/main.js' {
  declare module.exports: $Exports<'browserify/test/no_builtins/main'>;
}
declare module 'browserify/test/node_modules/beep/index.js' {
  declare module.exports: $Exports<'browserify/test/node_modules/beep/index'>;
}
declare module 'browserify/test/node_modules/plugin-foo/index.js' {
  declare module.exports: $Exports<'browserify/test/node_modules/plugin-foo/index'>;
}
declare module 'browserify/test/node_modules/tr/index.js' {
  declare module.exports: $Exports<'browserify/test/node_modules/tr/index'>;
}
declare module 'browserify/test/noparse.js' {
  declare module.exports: $Exports<'browserify/test/noparse'>;
}
declare module 'browserify/test/noparse/a.js' {
  declare module.exports: $Exports<'browserify/test/noparse/a'>;
}
declare module 'browserify/test/noparse/b.js' {
  declare module.exports: $Exports<'browserify/test/noparse/b'>;
}
declare module 'browserify/test/noparse/dir1/1.js' {
  declare module.exports: $Exports<'browserify/test/noparse/dir1/1'>;
}
declare module 'browserify/test/noparse/dir1/dir2/2.js' {
  declare module.exports: $Exports<'browserify/test/noparse/dir1/dir2/2'>;
}
declare module 'browserify/test/noparse/node_modules/robot/lib/beep.js' {
  declare module.exports: $Exports<'browserify/test/noparse/node_modules/robot/lib/beep'>;
}
declare module 'browserify/test/noparse/node_modules/robot/lib/boop.js' {
  declare module.exports: $Exports<'browserify/test/noparse/node_modules/robot/lib/boop'>;
}
declare module 'browserify/test/noparse/node_modules/robot/main.js' {
  declare module.exports: $Exports<'browserify/test/noparse/node_modules/robot/main'>;
}
declare module 'browserify/test/pack.js' {
  declare module.exports: $Exports<'browserify/test/pack'>;
}
declare module 'browserify/test/paths_transform.js' {
  declare module.exports: $Exports<'browserify/test/paths_transform'>;
}
declare module 'browserify/test/paths.js' {
  declare module.exports: $Exports<'browserify/test/paths'>;
}
declare module 'browserify/test/paths/main.js' {
  declare module.exports: $Exports<'browserify/test/paths/main'>;
}
declare module 'browserify/test/paths/x/aaa/index.js' {
  declare module.exports: $Exports<'browserify/test/paths/x/aaa/index'>;
}
declare module 'browserify/test/paths/x/ccc/index.js' {
  declare module.exports: $Exports<'browserify/test/paths/x/ccc/index'>;
}
declare module 'browserify/test/paths/y/bbb/index.js' {
  declare module.exports: $Exports<'browserify/test/paths/y/bbb/index'>;
}
declare module 'browserify/test/paths/y/ccc/index.js' {
  declare module.exports: $Exports<'browserify/test/paths/y/ccc/index'>;
}
declare module 'browserify/test/pipeline_deps.js' {
  declare module.exports: $Exports<'browserify/test/pipeline_deps'>;
}
declare module 'browserify/test/pipeline_deps/bar.js' {
  declare module.exports: $Exports<'browserify/test/pipeline_deps/bar'>;
}
declare module 'browserify/test/pipeline_deps/foo.js' {
  declare module.exports: $Exports<'browserify/test/pipeline_deps/foo'>;
}
declare module 'browserify/test/pipeline_deps/main.js' {
  declare module.exports: $Exports<'browserify/test/pipeline_deps/main'>;
}
declare module 'browserify/test/pipeline_deps/xyz.js' {
  declare module.exports: $Exports<'browserify/test/pipeline_deps/xyz'>;
}
declare module 'browserify/test/pkg_event.js' {
  declare module.exports: $Exports<'browserify/test/pkg_event'>;
}
declare module 'browserify/test/pkg_event/main.js' {
  declare module.exports: $Exports<'browserify/test/pkg_event/main'>;
}
declare module 'browserify/test/pkg.js' {
  declare module.exports: $Exports<'browserify/test/pkg'>;
}
declare module 'browserify/test/pkg/main.js' {
  declare module.exports: $Exports<'browserify/test/pkg/main'>;
}
declare module 'browserify/test/plugin.js' {
  declare module.exports: $Exports<'browserify/test/plugin'>;
}
declare module 'browserify/test/plugin/main.js' {
  declare module.exports: $Exports<'browserify/test/plugin/main'>;
}
declare module 'browserify/test/process.js' {
  declare module.exports: $Exports<'browserify/test/process'>;
}
declare module 'browserify/test/process/main.js' {
  declare module.exports: $Exports<'browserify/test/process/main'>;
}
declare module 'browserify/test/process/one.js' {
  declare module.exports: $Exports<'browserify/test/process/one'>;
}
declare module 'browserify/test/process/two.js' {
  declare module.exports: $Exports<'browserify/test/process/two'>;
}
declare module 'browserify/test/relative_dedupe.js' {
  declare module.exports: $Exports<'browserify/test/relative_dedupe'>;
}
declare module 'browserify/test/relative_dedupe/a/a.js' {
  declare module.exports: $Exports<'browserify/test/relative_dedupe/a/a'>;
}
declare module 'browserify/test/relative_dedupe/a/b.js' {
  declare module.exports: $Exports<'browserify/test/relative_dedupe/a/b'>;
}
declare module 'browserify/test/relative_dedupe/a/index.js' {
  declare module.exports: $Exports<'browserify/test/relative_dedupe/a/index'>;
}
declare module 'browserify/test/relative_dedupe/b/a.js' {
  declare module.exports: $Exports<'browserify/test/relative_dedupe/b/a'>;
}
declare module 'browserify/test/relative_dedupe/b/b.js' {
  declare module.exports: $Exports<'browserify/test/relative_dedupe/b/b'>;
}
declare module 'browserify/test/relative_dedupe/b/index.js' {
  declare module.exports: $Exports<'browserify/test/relative_dedupe/b/index'>;
}
declare module 'browserify/test/relative_dedupe/index.js' {
  declare module.exports: $Exports<'browserify/test/relative_dedupe/index'>;
}
declare module 'browserify/test/relative_dedupe/main.js' {
  declare module.exports: $Exports<'browserify/test/relative_dedupe/main'>;
}
declare module 'browserify/test/require_cache.js' {
  declare module.exports: $Exports<'browserify/test/require_cache'>;
}
declare module 'browserify/test/require_expose.js' {
  declare module.exports: $Exports<'browserify/test/require_expose'>;
}
declare module 'browserify/test/require_expose/main.js' {
  declare module.exports: $Exports<'browserify/test/require_expose/main'>;
}
declare module 'browserify/test/require_expose/some_dep.js' {
  declare module.exports: $Exports<'browserify/test/require_expose/some_dep'>;
}
declare module 'browserify/test/reset.js' {
  declare module.exports: $Exports<'browserify/test/reset'>;
}
declare module 'browserify/test/resolve_exposed.js' {
  declare module.exports: $Exports<'browserify/test/resolve_exposed'>;
}
declare module 'browserify/test/resolve_exposed/main.js' {
  declare module.exports: $Exports<'browserify/test/resolve_exposed/main'>;
}
declare module 'browserify/test/resolve_exposed/x.js' {
  declare module.exports: $Exports<'browserify/test/resolve_exposed/x'>;
}
declare module 'browserify/test/retarget.js' {
  declare module.exports: $Exports<'browserify/test/retarget'>;
}
declare module 'browserify/test/reverse_multi_bundle.js' {
  declare module.exports: $Exports<'browserify/test/reverse_multi_bundle'>;
}
declare module 'browserify/test/reverse_multi_bundle/app.js' {
  declare module.exports: $Exports<'browserify/test/reverse_multi_bundle/app'>;
}
declare module 'browserify/test/reverse_multi_bundle/arbitrary.js' {
  declare module.exports: $Exports<'browserify/test/reverse_multi_bundle/arbitrary'>;
}
declare module 'browserify/test/reverse_multi_bundle/lazy.js' {
  declare module.exports: $Exports<'browserify/test/reverse_multi_bundle/lazy'>;
}
declare module 'browserify/test/reverse_multi_bundle/shared.js' {
  declare module.exports: $Exports<'browserify/test/reverse_multi_bundle/shared'>;
}
declare module 'browserify/test/shared_symlink.js' {
  declare module.exports: $Exports<'browserify/test/shared_symlink'>;
}
declare module 'browserify/test/shared_symlink/app/index.js' {
  declare module.exports: $Exports<'browserify/test/shared_symlink/app/index'>;
}
declare module 'browserify/test/shared_symlink/app/node_modules/foo/index.js' {
  declare module.exports: $Exports<'browserify/test/shared_symlink/app/node_modules/foo/index'>;
}
declare module 'browserify/test/shared_symlink/main.js' {
  declare module.exports: $Exports<'browserify/test/shared_symlink/main'>;
}
declare module 'browserify/test/shared_symlink/shared/index.js' {
  declare module.exports: $Exports<'browserify/test/shared_symlink/shared/index'>;
}
declare module 'browserify/test/shebang.js' {
  declare module.exports: $Exports<'browserify/test/shebang'>;
}
declare module 'browserify/test/shebang/foo.js' {
  declare module.exports: $Exports<'browserify/test/shebang/foo'>;
}
declare module 'browserify/test/shebang/main.js' {
  declare module.exports: $Exports<'browserify/test/shebang/main'>;
}
declare module 'browserify/test/standalone_events.js' {
  declare module.exports: $Exports<'browserify/test/standalone_events'>;
}
declare module 'browserify/test/standalone_sourcemap.js' {
  declare module.exports: $Exports<'browserify/test/standalone_sourcemap'>;
}
declare module 'browserify/test/standalone.js' {
  declare module.exports: $Exports<'browserify/test/standalone'>;
}
declare module 'browserify/test/standalone/main.js' {
  declare module.exports: $Exports<'browserify/test/standalone/main'>;
}
declare module 'browserify/test/standalone/one.js' {
  declare module.exports: $Exports<'browserify/test/standalone/one'>;
}
declare module 'browserify/test/standalone/two.js' {
  declare module.exports: $Exports<'browserify/test/standalone/two'>;
}
declare module 'browserify/test/stdin.js' {
  declare module.exports: $Exports<'browserify/test/stdin'>;
}
declare module 'browserify/test/stream_file.js' {
  declare module.exports: $Exports<'browserify/test/stream_file'>;
}
declare module 'browserify/test/stream.js' {
  declare module.exports: $Exports<'browserify/test/stream'>;
}
declare module 'browserify/test/stream/bar.js' {
  declare module.exports: $Exports<'browserify/test/stream/bar'>;
}
declare module 'browserify/test/stream/foo.js' {
  declare module.exports: $Exports<'browserify/test/stream/foo'>;
}
declare module 'browserify/test/stream/main.js' {
  declare module.exports: $Exports<'browserify/test/stream/main'>;
}
declare module 'browserify/test/subdep.js' {
  declare module.exports: $Exports<'browserify/test/subdep'>;
}
declare module 'browserify/test/subdep/index.js' {
  declare module.exports: $Exports<'browserify/test/subdep/index'>;
}
declare module 'browserify/test/symlink_dedupe.js' {
  declare module.exports: $Exports<'browserify/test/symlink_dedupe'>;
}
declare module 'browserify/test/symlink_dedupe/main.js' {
  declare module.exports: $Exports<'browserify/test/symlink_dedupe/main'>;
}
declare module 'browserify/test/symlink_dedupe/one/f.js' {
  declare module.exports: $Exports<'browserify/test/symlink_dedupe/one/f'>;
}
declare module 'browserify/test/symlink_dedupe/one/g.js' {
  declare module.exports: $Exports<'browserify/test/symlink_dedupe/one/g'>;
}
declare module 'browserify/test/syntax_cache.js' {
  declare module.exports: $Exports<'browserify/test/syntax_cache'>;
}
declare module 'browserify/test/syntax_cache/invalid.js' {
  declare module.exports: $Exports<'browserify/test/syntax_cache/invalid'>;
}
declare module 'browserify/test/syntax_cache/valid.js' {
  declare module.exports: $Exports<'browserify/test/syntax_cache/valid'>;
}
declare module 'browserify/test/tr_args.js' {
  declare module.exports: $Exports<'browserify/test/tr_args'>;
}
declare module 'browserify/test/tr_args/main.js' {
  declare module.exports: $Exports<'browserify/test/tr_args/main'>;
}
declare module 'browserify/test/tr_args/tr.js' {
  declare module.exports: $Exports<'browserify/test/tr_args/tr'>;
}
declare module 'browserify/test/tr_error.js' {
  declare module.exports: $Exports<'browserify/test/tr_error'>;
}
declare module 'browserify/test/tr_flags.js' {
  declare module.exports: $Exports<'browserify/test/tr_flags'>;
}
declare module 'browserify/test/tr_global.js' {
  declare module.exports: $Exports<'browserify/test/tr_global'>;
}
declare module 'browserify/test/tr_global/main.js' {
  declare module.exports: $Exports<'browserify/test/tr_global/main'>;
}
declare module 'browserify/test/tr_global/node_modules/tr/index.js' {
  declare module.exports: $Exports<'browserify/test/tr_global/node_modules/tr/index'>;
}
declare module 'browserify/test/tr_global/node_modules/x/index.js' {
  declare module.exports: $Exports<'browserify/test/tr_global/node_modules/x/index'>;
}
declare module 'browserify/test/tr_global/node_modules/x/node_modules/tr/index.js' {
  declare module.exports: $Exports<'browserify/test/tr_global/node_modules/x/node_modules/tr/index'>;
}
declare module 'browserify/test/tr_no_entry.js' {
  declare module.exports: $Exports<'browserify/test/tr_no_entry'>;
}
declare module 'browserify/test/tr_no_entry/main.js' {
  declare module.exports: $Exports<'browserify/test/tr_no_entry/main'>;
}
declare module 'browserify/test/tr_once.js' {
  declare module.exports: $Exports<'browserify/test/tr_once'>;
}
declare module 'browserify/test/tr_once/main.js' {
  declare module.exports: $Exports<'browserify/test/tr_once/main'>;
}
declare module 'browserify/test/tr_order.js' {
  declare module.exports: $Exports<'browserify/test/tr_order'>;
}
declare module 'browserify/test/tr_order/replace_aaa.js' {
  declare module.exports: $Exports<'browserify/test/tr_order/replace_aaa'>;
}
declare module 'browserify/test/tr_order/replace_bbb.js' {
  declare module.exports: $Exports<'browserify/test/tr_order/replace_bbb'>;
}
declare module 'browserify/test/tr_symlink.js' {
  declare module.exports: $Exports<'browserify/test/tr_symlink'>;
}
declare module 'browserify/test/tr_symlink/a-module/index.js' {
  declare module.exports: $Exports<'browserify/test/tr_symlink/a-module/index'>;
}
declare module 'browserify/test/tr_symlink/app/main.js' {
  declare module.exports: $Exports<'browserify/test/tr_symlink/app/main'>;
}
declare module 'browserify/test/tr_symlink/b-module/ext.js' {
  declare module.exports: $Exports<'browserify/test/tr_symlink/b-module/ext'>;
}
declare module 'browserify/test/tr_symlink/b-module/index.js' {
  declare module.exports: $Exports<'browserify/test/tr_symlink/b-module/index'>;
}
declare module 'browserify/test/tr.js' {
  declare module.exports: $Exports<'browserify/test/tr'>;
}
declare module 'browserify/test/tr/f.js' {
  declare module.exports: $Exports<'browserify/test/tr/f'>;
}
declare module 'browserify/test/tr/main.js' {
  declare module.exports: $Exports<'browserify/test/tr/main'>;
}
declare module 'browserify/test/tr/subdir/g.js' {
  declare module.exports: $Exports<'browserify/test/tr/subdir/g'>;
}
declare module 'browserify/test/unicode.js' {
  declare module.exports: $Exports<'browserify/test/unicode'>;
}
declare module 'browserify/test/unicode/main.js' {
  declare module.exports: $Exports<'browserify/test/unicode/main'>;
}
declare module 'browserify/test/unicode/one.js' {
  declare module.exports: $Exports<'browserify/test/unicode/one'>;
}
declare module 'browserify/test/unicode/two.js' {
  declare module.exports: $Exports<'browserify/test/unicode/two'>;
}
declare module 'browserify/test/util.js' {
  declare module.exports: $Exports<'browserify/test/util'>;
}
declare module 'browserify/test/yield.js' {
  declare module.exports: $Exports<'browserify/test/yield'>;
}
declare module 'browserify/test/yield/f.js' {
  declare module.exports: $Exports<'browserify/test/yield/f'>;
}
declare module 'browserify/test/yield/main.js' {
  declare module.exports: $Exports<'browserify/test/yield/main'>;
}
