// flow-typed signature: 04741f0cf6523d0d8f58715472154748
// flow-typed version: <<STUB>>/chai_v^4.0.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chai'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chai' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chai/chai' {
  declare module.exports: any;
}

declare module 'chai/karma.conf' {
  declare module.exports: any;
}

declare module 'chai/karma.sauce' {
  declare module.exports: any;
}

declare module 'chai/lib/chai' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/assertion' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/config' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/core/assertions' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/interface/assert' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/interface/expect' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/interface/should' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/addChainableMethod' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/addMethod' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/addProperty' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/expectTypes' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/flag' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/getActual' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/getEnumerableProperties' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/getMessage' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/getName' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/getPathInfo' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/getPathValue' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/getProperties' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/hasProperty' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/index' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/inspect' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/objDisplay' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/overwriteChainableMethod' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/overwriteMethod' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/overwriteProperty' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/test' {
  declare module.exports: any;
}

declare module 'chai/lib/chai/utils/transferFlags' {
  declare module.exports: any;
}

declare module 'chai/sauce.browsers' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chai/chai.js' {
  declare module.exports: $Exports<'chai/chai'>;
}
declare module 'chai/index' {
  declare module.exports: $Exports<'chai'>;
}
declare module 'chai/index.js' {
  declare module.exports: $Exports<'chai'>;
}
declare module 'chai/karma.conf.js' {
  declare module.exports: $Exports<'chai/karma.conf'>;
}
declare module 'chai/karma.sauce.js' {
  declare module.exports: $Exports<'chai/karma.sauce'>;
}
declare module 'chai/lib/chai.js' {
  declare module.exports: $Exports<'chai/lib/chai'>;
}
declare module 'chai/lib/chai/assertion.js' {
  declare module.exports: $Exports<'chai/lib/chai/assertion'>;
}
declare module 'chai/lib/chai/config.js' {
  declare module.exports: $Exports<'chai/lib/chai/config'>;
}
declare module 'chai/lib/chai/core/assertions.js' {
  declare module.exports: $Exports<'chai/lib/chai/core/assertions'>;
}
declare module 'chai/lib/chai/interface/assert.js' {
  declare module.exports: $Exports<'chai/lib/chai/interface/assert'>;
}
declare module 'chai/lib/chai/interface/expect.js' {
  declare module.exports: $Exports<'chai/lib/chai/interface/expect'>;
}
declare module 'chai/lib/chai/interface/should.js' {
  declare module.exports: $Exports<'chai/lib/chai/interface/should'>;
}
declare module 'chai/lib/chai/utils/addChainableMethod.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/addChainableMethod'>;
}
declare module 'chai/lib/chai/utils/addMethod.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/addMethod'>;
}
declare module 'chai/lib/chai/utils/addProperty.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/addProperty'>;
}
declare module 'chai/lib/chai/utils/expectTypes.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/expectTypes'>;
}
declare module 'chai/lib/chai/utils/flag.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/flag'>;
}
declare module 'chai/lib/chai/utils/getActual.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/getActual'>;
}
declare module 'chai/lib/chai/utils/getEnumerableProperties.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/getEnumerableProperties'>;
}
declare module 'chai/lib/chai/utils/getMessage.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/getMessage'>;
}
declare module 'chai/lib/chai/utils/getName.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/getName'>;
}
declare module 'chai/lib/chai/utils/getPathInfo.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/getPathInfo'>;
}
declare module 'chai/lib/chai/utils/getPathValue.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/getPathValue'>;
}
declare module 'chai/lib/chai/utils/getProperties.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/getProperties'>;
}
declare module 'chai/lib/chai/utils/hasProperty.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/hasProperty'>;
}
declare module 'chai/lib/chai/utils/index.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/index'>;
}
declare module 'chai/lib/chai/utils/inspect.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/inspect'>;
}
declare module 'chai/lib/chai/utils/objDisplay.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/objDisplay'>;
}
declare module 'chai/lib/chai/utils/overwriteChainableMethod.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/overwriteChainableMethod'>;
}
declare module 'chai/lib/chai/utils/overwriteMethod.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/overwriteMethod'>;
}
declare module 'chai/lib/chai/utils/overwriteProperty.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/overwriteProperty'>;
}
declare module 'chai/lib/chai/utils/test.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/test'>;
}
declare module 'chai/lib/chai/utils/transferFlags.js' {
  declare module.exports: $Exports<'chai/lib/chai/utils/transferFlags'>;
}
declare module 'chai/sauce.browsers.js' {
  declare module.exports: $Exports<'chai/sauce.browsers'>;
}
