// flow-typed signature: c9ff5069b7480eab75d8eacc9e00c59d
// flow-typed version: <<STUB>>/es6-promise_v^4.0.4/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'es6-promise'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'es6-promise' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'es6-promise/auto' {
  declare module.exports: any;
}

declare module 'es6-promise/dist/es6-promise.auto' {
  declare module.exports: any;
}

declare module 'es6-promise/dist/es6-promise.auto.min' {
  declare module.exports: any;
}

declare module 'es6-promise/dist/es6-promise' {
  declare module.exports: any;
}

declare module 'es6-promise/dist/es6-promise.min' {
  declare module.exports: any;
}

declare module 'es6-promise/lib/es6-promise.auto' {
  declare module.exports: any;
}

declare module 'es6-promise/lib/es6-promise' {
  declare module.exports: any;
}

declare module 'es6-promise/lib/es6-promise/-internal' {
  declare module.exports: any;
}

declare module 'es6-promise/lib/es6-promise/asap' {
  declare module.exports: any;
}

declare module 'es6-promise/lib/es6-promise/enumerator' {
  declare module.exports: any;
}

declare module 'es6-promise/lib/es6-promise/polyfill' {
  declare module.exports: any;
}

declare module 'es6-promise/lib/es6-promise/promise' {
  declare module.exports: any;
}

declare module 'es6-promise/lib/es6-promise/promise/all' {
  declare module.exports: any;
}

declare module 'es6-promise/lib/es6-promise/promise/race' {
  declare module.exports: any;
}

declare module 'es6-promise/lib/es6-promise/promise/reject' {
  declare module.exports: any;
}

declare module 'es6-promise/lib/es6-promise/promise/resolve' {
  declare module.exports: any;
}

declare module 'es6-promise/lib/es6-promise/then' {
  declare module.exports: any;
}

declare module 'es6-promise/lib/es6-promise/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'es6-promise/auto.js' {
  declare module.exports: $Exports<'es6-promise/auto'>;
}
declare module 'es6-promise/dist/es6-promise.auto.js' {
  declare module.exports: $Exports<'es6-promise/dist/es6-promise.auto'>;
}
declare module 'es6-promise/dist/es6-promise.auto.min.js' {
  declare module.exports: $Exports<'es6-promise/dist/es6-promise.auto.min'>;
}
declare module 'es6-promise/dist/es6-promise.js' {
  declare module.exports: $Exports<'es6-promise/dist/es6-promise'>;
}
declare module 'es6-promise/dist/es6-promise.min.js' {
  declare module.exports: $Exports<'es6-promise/dist/es6-promise.min'>;
}
declare module 'es6-promise/lib/es6-promise.auto.js' {
  declare module.exports: $Exports<'es6-promise/lib/es6-promise.auto'>;
}
declare module 'es6-promise/lib/es6-promise.js' {
  declare module.exports: $Exports<'es6-promise/lib/es6-promise'>;
}
declare module 'es6-promise/lib/es6-promise/-internal.js' {
  declare module.exports: $Exports<'es6-promise/lib/es6-promise/-internal'>;
}
declare module 'es6-promise/lib/es6-promise/asap.js' {
  declare module.exports: $Exports<'es6-promise/lib/es6-promise/asap'>;
}
declare module 'es6-promise/lib/es6-promise/enumerator.js' {
  declare module.exports: $Exports<'es6-promise/lib/es6-promise/enumerator'>;
}
declare module 'es6-promise/lib/es6-promise/polyfill.js' {
  declare module.exports: $Exports<'es6-promise/lib/es6-promise/polyfill'>;
}
declare module 'es6-promise/lib/es6-promise/promise.js' {
  declare module.exports: $Exports<'es6-promise/lib/es6-promise/promise'>;
}
declare module 'es6-promise/lib/es6-promise/promise/all.js' {
  declare module.exports: $Exports<'es6-promise/lib/es6-promise/promise/all'>;
}
declare module 'es6-promise/lib/es6-promise/promise/race.js' {
  declare module.exports: $Exports<'es6-promise/lib/es6-promise/promise/race'>;
}
declare module 'es6-promise/lib/es6-promise/promise/reject.js' {
  declare module.exports: $Exports<'es6-promise/lib/es6-promise/promise/reject'>;
}
declare module 'es6-promise/lib/es6-promise/promise/resolve.js' {
  declare module.exports: $Exports<'es6-promise/lib/es6-promise/promise/resolve'>;
}
declare module 'es6-promise/lib/es6-promise/then.js' {
  declare module.exports: $Exports<'es6-promise/lib/es6-promise/then'>;
}
declare module 'es6-promise/lib/es6-promise/utils.js' {
  declare module.exports: $Exports<'es6-promise/lib/es6-promise/utils'>;
}
