// flow-typed signature: ee880f64f2079a01360b7a837f996525
// flow-typed version: <<STUB>>/fetch-mock_v^5.10.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'fetch-mock'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'fetch-mock' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'fetch-mock/es5/client-browserified' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/client' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/compile-route' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/fetch-mock' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/server' {
  declare module.exports: any;
}

declare module 'fetch-mock/es5/status-text' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/client' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/compile-route' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/fetch-mock' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/server' {
  declare module.exports: any;
}

declare module 'fetch-mock/src/status-text' {
  declare module.exports: any;
}

// Filename aliases
declare module 'fetch-mock/es5/client-browserified.js' {
  declare module.exports: $Exports<'fetch-mock/es5/client-browserified'>;
}
declare module 'fetch-mock/es5/client.js' {
  declare module.exports: $Exports<'fetch-mock/es5/client'>;
}
declare module 'fetch-mock/es5/compile-route.js' {
  declare module.exports: $Exports<'fetch-mock/es5/compile-route'>;
}
declare module 'fetch-mock/es5/fetch-mock.js' {
  declare module.exports: $Exports<'fetch-mock/es5/fetch-mock'>;
}
declare module 'fetch-mock/es5/server.js' {
  declare module.exports: $Exports<'fetch-mock/es5/server'>;
}
declare module 'fetch-mock/es5/status-text.js' {
  declare module.exports: $Exports<'fetch-mock/es5/status-text'>;
}
declare module 'fetch-mock/src/client.js' {
  declare module.exports: $Exports<'fetch-mock/src/client'>;
}
declare module 'fetch-mock/src/compile-route.js' {
  declare module.exports: $Exports<'fetch-mock/src/compile-route'>;
}
declare module 'fetch-mock/src/fetch-mock.js' {
  declare module.exports: $Exports<'fetch-mock/src/fetch-mock'>;
}
declare module 'fetch-mock/src/server.js' {
  declare module.exports: $Exports<'fetch-mock/src/server'>;
}
declare module 'fetch-mock/src/status-text.js' {
  declare module.exports: $Exports<'fetch-mock/src/status-text'>;
}
