// flow-typed signature: 9fbbd93f9ee93079421a30befcc27a41
// flow-typed version: <<STUB>>/graphql-tag_v^2.0.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-tag'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-tag' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-tag/lib/graphql-tag.umd' {
  declare module.exports: any;
}

declare module 'graphql-tag/loader' {
  declare module.exports: any;
}

declare module 'graphql-tag/src/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-tag/lib/graphql-tag.umd.js' {
  declare module.exports: $Exports<'graphql-tag/lib/graphql-tag.umd'>;
}
declare module 'graphql-tag/loader.js' {
  declare module.exports: $Exports<'graphql-tag/loader'>;
}
declare module 'graphql-tag/src/index.js' {
  declare module.exports: $Exports<'graphql-tag/src/index'>;
}
