// flow-typed signature: 591f5cc769a3eef28c4324709a7b1bb9
// flow-typed version: <<STUB>>/graphql-anywhere_v^3.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'graphql-anywhere'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'graphql-anywhere' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'graphql-anywhere/lib/src/directives' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/src/getFromAST' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/src/graphql' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/src/index' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/src/storeUtils' {
  declare module.exports: any;
}

declare module 'graphql-anywhere/lib/src/utilities' {
  declare module.exports: any;
}

// Filename aliases
declare module 'graphql-anywhere/lib/src/directives.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/src/directives'>;
}
declare module 'graphql-anywhere/lib/src/getFromAST.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/src/getFromAST'>;
}
declare module 'graphql-anywhere/lib/src/graphql.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/src/graphql'>;
}
declare module 'graphql-anywhere/lib/src/index.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/src/index'>;
}
declare module 'graphql-anywhere/lib/src/storeUtils.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/src/storeUtils'>;
}
declare module 'graphql-anywhere/lib/src/utilities.js' {
  declare module.exports: $Exports<'graphql-anywhere/lib/src/utilities'>;
}
