// flow-typed signature: 16e61387d3e071d9040559096e70378d
// flow-typed version: <<STUB>>/grunt_v1.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt/lib/grunt' {
  declare module.exports: any;
}

declare module 'grunt/lib/grunt/cli' {
  declare module.exports: any;
}

declare module 'grunt/lib/grunt/config' {
  declare module.exports: any;
}

declare module 'grunt/lib/grunt/event' {
  declare module.exports: any;
}

declare module 'grunt/lib/grunt/fail' {
  declare module.exports: any;
}

declare module 'grunt/lib/grunt/file' {
  declare module.exports: any;
}

declare module 'grunt/lib/grunt/help' {
  declare module.exports: any;
}

declare module 'grunt/lib/grunt/option' {
  declare module.exports: any;
}

declare module 'grunt/lib/grunt/task' {
  declare module.exports: any;
}

declare module 'grunt/lib/grunt/template' {
  declare module.exports: any;
}

declare module 'grunt/lib/util/task' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt/lib/grunt.js' {
  declare module.exports: $Exports<'grunt/lib/grunt'>;
}
declare module 'grunt/lib/grunt/cli.js' {
  declare module.exports: $Exports<'grunt/lib/grunt/cli'>;
}
declare module 'grunt/lib/grunt/config.js' {
  declare module.exports: $Exports<'grunt/lib/grunt/config'>;
}
declare module 'grunt/lib/grunt/event.js' {
  declare module.exports: $Exports<'grunt/lib/grunt/event'>;
}
declare module 'grunt/lib/grunt/fail.js' {
  declare module.exports: $Exports<'grunt/lib/grunt/fail'>;
}
declare module 'grunt/lib/grunt/file.js' {
  declare module.exports: $Exports<'grunt/lib/grunt/file'>;
}
declare module 'grunt/lib/grunt/help.js' {
  declare module.exports: $Exports<'grunt/lib/grunt/help'>;
}
declare module 'grunt/lib/grunt/option.js' {
  declare module.exports: $Exports<'grunt/lib/grunt/option'>;
}
declare module 'grunt/lib/grunt/task.js' {
  declare module.exports: $Exports<'grunt/lib/grunt/task'>;
}
declare module 'grunt/lib/grunt/template.js' {
  declare module.exports: $Exports<'grunt/lib/grunt/template'>;
}
declare module 'grunt/lib/util/task.js' {
  declare module.exports: $Exports<'grunt/lib/util/task'>;
}
