// flow-typed signature: 45a523f4c24ceae9bc0dac8195faaeea
// flow-typed version: <<STUB>>/grunt-tslint_v^5.0.1/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'grunt-tslint'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'grunt-tslint' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'grunt-tslint/Gruntfile' {
  declare module.exports: any;
}

declare module 'grunt-tslint/tasks/tslint' {
  declare module.exports: any;
}

// Filename aliases
declare module 'grunt-tslint/Gruntfile.js' {
  declare module.exports: $Exports<'grunt-tslint/Gruntfile'>;
}
declare module 'grunt-tslint/tasks/tslint.js' {
  declare module.exports: $Exports<'grunt-tslint/tasks/tslint'>;
}
