// flow-typed signature: 265747b92601fbc38438ee0fd2f6518b
// flow-typed version: <<STUB>>/remap-istanbul_v0.8.0/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remap-istanbul'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'remap-istanbul' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'remap-istanbul/lib/CoverageTransformer' {
  declare module.exports: any;
}

declare module 'remap-istanbul/lib/getMapping' {
  declare module.exports: any;
}

declare module 'remap-istanbul/lib/gruntRemapIstanbul' {
  declare module.exports: any;
}

declare module 'remap-istanbul/lib/gulpRemapIstanbul' {
  declare module.exports: any;
}

declare module 'remap-istanbul/lib/intern-reporters/JsonCoverage' {
  declare module.exports: any;
}

declare module 'remap-istanbul/lib/loadCoverage' {
  declare module.exports: any;
}

declare module 'remap-istanbul/lib/main' {
  declare module.exports: any;
}

declare module 'remap-istanbul/lib/remap-istanbul' {
  declare module.exports: any;
}

declare module 'remap-istanbul/lib/remap' {
  declare module.exports: any;
}

declare module 'remap-istanbul/lib/remapBranch' {
  declare module.exports: any;
}

declare module 'remap-istanbul/lib/remapFunction' {
  declare module.exports: any;
}

declare module 'remap-istanbul/lib/SparceCoverageCollector' {
  declare module.exports: any;
}

declare module 'remap-istanbul/lib/writeReport' {
  declare module.exports: any;
}

declare module 'remap-istanbul/src/CoverageTransformer' {
  declare module.exports: any;
}

declare module 'remap-istanbul/src/getMapping' {
  declare module.exports: any;
}

declare module 'remap-istanbul/src/gruntRemapIstanbul' {
  declare module.exports: any;
}

declare module 'remap-istanbul/src/gulpRemapIstanbul' {
  declare module.exports: any;
}

declare module 'remap-istanbul/src/intern-reporters/JsonCoverage' {
  declare module.exports: any;
}

declare module 'remap-istanbul/src/loadCoverage' {
  declare module.exports: any;
}

declare module 'remap-istanbul/src/main' {
  declare module.exports: any;
}

declare module 'remap-istanbul/src/remap-istanbul' {
  declare module.exports: any;
}

declare module 'remap-istanbul/src/remap' {
  declare module.exports: any;
}

declare module 'remap-istanbul/src/remapBranch' {
  declare module.exports: any;
}

declare module 'remap-istanbul/src/remapFunction' {
  declare module.exports: any;
}

declare module 'remap-istanbul/src/SparceCoverageCollector' {
  declare module.exports: any;
}

declare module 'remap-istanbul/src/writeReport' {
  declare module.exports: any;
}

declare module 'remap-istanbul/tasks/remapIstanbul' {
  declare module.exports: any;
}

// Filename aliases
declare module 'remap-istanbul/lib/CoverageTransformer.js' {
  declare module.exports: $Exports<'remap-istanbul/lib/CoverageTransformer'>;
}
declare module 'remap-istanbul/lib/getMapping.js' {
  declare module.exports: $Exports<'remap-istanbul/lib/getMapping'>;
}
declare module 'remap-istanbul/lib/gruntRemapIstanbul.js' {
  declare module.exports: $Exports<'remap-istanbul/lib/gruntRemapIstanbul'>;
}
declare module 'remap-istanbul/lib/gulpRemapIstanbul.js' {
  declare module.exports: $Exports<'remap-istanbul/lib/gulpRemapIstanbul'>;
}
declare module 'remap-istanbul/lib/intern-reporters/JsonCoverage.js' {
  declare module.exports: $Exports<'remap-istanbul/lib/intern-reporters/JsonCoverage'>;
}
declare module 'remap-istanbul/lib/loadCoverage.js' {
  declare module.exports: $Exports<'remap-istanbul/lib/loadCoverage'>;
}
declare module 'remap-istanbul/lib/main.js' {
  declare module.exports: $Exports<'remap-istanbul/lib/main'>;
}
declare module 'remap-istanbul/lib/remap-istanbul.js' {
  declare module.exports: $Exports<'remap-istanbul/lib/remap-istanbul'>;
}
declare module 'remap-istanbul/lib/remap.js' {
  declare module.exports: $Exports<'remap-istanbul/lib/remap'>;
}
declare module 'remap-istanbul/lib/remapBranch.js' {
  declare module.exports: $Exports<'remap-istanbul/lib/remapBranch'>;
}
declare module 'remap-istanbul/lib/remapFunction.js' {
  declare module.exports: $Exports<'remap-istanbul/lib/remapFunction'>;
}
declare module 'remap-istanbul/lib/SparceCoverageCollector.js' {
  declare module.exports: $Exports<'remap-istanbul/lib/SparceCoverageCollector'>;
}
declare module 'remap-istanbul/lib/writeReport.js' {
  declare module.exports: $Exports<'remap-istanbul/lib/writeReport'>;
}
declare module 'remap-istanbul/src/CoverageTransformer.js' {
  declare module.exports: $Exports<'remap-istanbul/src/CoverageTransformer'>;
}
declare module 'remap-istanbul/src/getMapping.js' {
  declare module.exports: $Exports<'remap-istanbul/src/getMapping'>;
}
declare module 'remap-istanbul/src/gruntRemapIstanbul.js' {
  declare module.exports: $Exports<'remap-istanbul/src/gruntRemapIstanbul'>;
}
declare module 'remap-istanbul/src/gulpRemapIstanbul.js' {
  declare module.exports: $Exports<'remap-istanbul/src/gulpRemapIstanbul'>;
}
declare module 'remap-istanbul/src/intern-reporters/JsonCoverage.js' {
  declare module.exports: $Exports<'remap-istanbul/src/intern-reporters/JsonCoverage'>;
}
declare module 'remap-istanbul/src/loadCoverage.js' {
  declare module.exports: $Exports<'remap-istanbul/src/loadCoverage'>;
}
declare module 'remap-istanbul/src/main.js' {
  declare module.exports: $Exports<'remap-istanbul/src/main'>;
}
declare module 'remap-istanbul/src/remap-istanbul.js' {
  declare module.exports: $Exports<'remap-istanbul/src/remap-istanbul'>;
}
declare module 'remap-istanbul/src/remap.js' {
  declare module.exports: $Exports<'remap-istanbul/src/remap'>;
}
declare module 'remap-istanbul/src/remapBranch.js' {
  declare module.exports: $Exports<'remap-istanbul/src/remapBranch'>;
}
declare module 'remap-istanbul/src/remapFunction.js' {
  declare module.exports: $Exports<'remap-istanbul/src/remapFunction'>;
}
declare module 'remap-istanbul/src/SparceCoverageCollector.js' {
  declare module.exports: $Exports<'remap-istanbul/src/SparceCoverageCollector'>;
}
declare module 'remap-istanbul/src/writeReport.js' {
  declare module.exports: $Exports<'remap-istanbul/src/writeReport'>;
}
declare module 'remap-istanbul/tasks/remapIstanbul.js' {
  declare module.exports: $Exports<'remap-istanbul/tasks/remapIstanbul'>;
}
