// flow-typed signature: d97be541e5468509a6b513cc93161de2
// flow-typed version: <<STUB>>/symbol-observable_v^1.0.2/flow_v0.48.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'symbol-observable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'symbol-observable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'symbol-observable/es/index' {
  declare module.exports: any;
}

declare module 'symbol-observable/es/ponyfill' {
  declare module.exports: any;
}

declare module 'symbol-observable/lib/index' {
  declare module.exports: any;
}

declare module 'symbol-observable/lib/ponyfill' {
  declare module.exports: any;
}

// Filename aliases
declare module 'symbol-observable/es/index.js' {
  declare module.exports: $Exports<'symbol-observable/es/index'>;
}
declare module 'symbol-observable/es/ponyfill.js' {
  declare module.exports: $Exports<'symbol-observable/es/ponyfill'>;
}
declare module 'symbol-observable/index' {
  declare module.exports: $Exports<'symbol-observable'>;
}
declare module 'symbol-observable/index.js' {
  declare module.exports: $Exports<'symbol-observable'>;
}
declare module 'symbol-observable/lib/index.js' {
  declare module.exports: $Exports<'symbol-observable/lib/index'>;
}
declare module 'symbol-observable/lib/ponyfill.js' {
  declare module.exports: $Exports<'symbol-observable/lib/ponyfill'>;
}
