module.exports = [
  { dirs: [], bundleName: "main" },
  { dirs: ['cache'] },
  { dirs: ['core'] },
  { dirs: ['errors'] },
  { dirs: ['link', 'batch'] },
  { dirs: ['link', 'batch-http'] },
  { dirs: ['link', 'context'] },
  { dirs: ['link', 'core'] },
  { dirs: ['link', 'error'] },
  { dirs: ['link', 'http'] },
  { dirs: ['link', 'retry'] },
  { dirs: ['link', 'schema'] },
  { dirs: ['link', 'utils'] },
  { dirs: ['link', 'ws'] },
  { dirs: ['react'] },
  { dirs: ['react', 'components'] },
  { dirs: ['react', 'context'] },
  { dirs: ['react', 'data'] },
  { dirs: ['react', 'hoc'] },
  { dirs: ['react', 'hooks'] },
  { dirs: ['react', 'parser'] },
  { dirs: ['react', 'ssr'] },
  { dirs: ['utilities'] },
  { dirs: ['testing'], extensions: [".js", ".jsx"] },
];
