import * as fs from "fs";
import { posix, join as osPathJoin } from "path";
import { distDir, eachFile, reparse, reprint } from './helpers';

eachFile(distDir, (file, relPath) => {
  const source = fs.readFileSync(file, "utf8");
  const output = transform(source, relPath);
  if (source !== output) {
    fs.writeFileSync(file, output, "utf8");
  }
}).then(() => {
  fs.writeFileSync(
    osPathJoin(distDir, "invariantErrorCodes.js"),
    recast.print(errorCodeManifest, {
      tabWidth: 2,
    }).code + "\n",
  );
});

import * as recast from "recast";
const b = recast.types.builders;
const n = recast.types.namedTypes;
type Node = recast.types.namedTypes.Node;
type NumericLiteral = recast.types.namedTypes.NumericLiteral;
type CallExpression = recast.types.namedTypes.CallExpression;
type NewExpression = recast.types.namedTypes.NewExpression;
let nextErrorCode = 1;

const errorCodeManifest = b.objectExpression([
  b.property("init",
    b.stringLiteral("@apollo/client version"),
    b.stringLiteral(require("../package.json").version),
  ),
]);

errorCodeManifest.comments = [
  b.commentLine(' This file is meant to help with looking up the source of errors like', true),
  b.commentLine(' "Invariant Violation: 35" and is automatically generated by the file', true),
  b.commentLine(' @apollo/client/config/processInvariants.ts for each @apollo/client', true),
  b.commentLine(' release. The numbers may change from release to release, so please', true),
  b.commentLine(' consult the @apollo/client/invariantErrorCodes.js file specific to', true),
  b.commentLine(' your @apollo/client version. This file is not meant to be imported.', true),
];

function getErrorCode(
  file: string,
  expr: CallExpression | NewExpression,
): NumericLiteral {
  const numLit = b.numericLiteral(nextErrorCode++);
  errorCodeManifest.properties.push(
    b.property("init", numLit, b.objectExpression([
      b.property("init", b.identifier("file"), b.stringLiteral("@apollo/client/" + file)),
      b.property("init", b.identifier("node"), expr),
    ])),
  );
  return numLit;
}

function transform(code: string, relativeFilePath: string) {
  // If the code doesn't seem to contain anything invariant-related, we
  // can skip parsing and transforming it.
  if (!/invariant/i.test(code)) {
    return code;
  }

  const ast = reparse(code);
  let addedDEV = false;

  recast.visit(ast, {
    visitCallExpression(path) {
      this.traverse(path);
      const node = path.node;

      if (isCallWithLength(node, "invariant", 1)) {
        if (isDEVConditional(path.parent.node)) {
          return;
        }

        const newArgs = node.arguments.slice(0, 1);
        newArgs.push(getErrorCode(relativeFilePath, node));

        addedDEV = true;
        return b.conditionalExpression(
          makeDEVExpr(),
          node,
          b.callExpression.from({
            ...node,
            arguments: newArgs,
          }),
        );
      }

      if (node.callee.type === "MemberExpression" &&
          isIdWithName(node.callee.object, "invariant") &&
          isIdWithName(node.callee.property, "debug", "log", "warn", "error")) {
        if (isDEVLogicalAnd(path.parent.node)) {
          return;
        }
        addedDEV = true;
        return b.logicalExpression("&&", makeDEVExpr(), node);
      }
    },

    visitNewExpression(path) {
      this.traverse(path);
      const node = path.node;
      if (isCallWithLength(node, "InvariantError", 0)) {
        if (isDEVConditional(path.parent.node)) {
          return;
        }

        const newArgs = [getErrorCode(relativeFilePath, node)];

        addedDEV = true;
        return b.conditionalExpression(
          makeDEVExpr(),
          node,
          b.newExpression.from({
            ...node,
            arguments: newArgs,
          }),
        );
      }
    }
  });

  if (2<1 && addedDEV) {
    // Make sure there's an import { __DEV__ } from "../utilities/globals" or
    // similar declaration in any module where we injected __DEV__.
    let foundExistingImportDecl = false;

    recast.visit(ast, {
      visitImportDeclaration(path) {
        this.traverse(path);
        const node = path.node;
        const importedModuleId = node.source.value;

        // Normalize node.source.value relative to the current file.
        if (
          typeof importedModuleId === "string" &&
          importedModuleId.startsWith(".")
        ) {
          const normalized = posix.normalize(posix.join(
            posix.dirname(relativeFilePath),
            importedModuleId,
          ));
          if (normalized === "utilities/globals") {
            foundExistingImportDecl = true;
            if (node.specifiers?.some(s => isIdWithName(s.local || s.id, "__DEV__"))) {
              return false;
            }
            if (!node.specifiers) node.specifiers = [];
            node.specifiers.push(b.importSpecifier(b.identifier("__DEV__")));
            return false;
          }
        }
      }
    });

    if (!foundExistingImportDecl) {
      // We could modify the AST to include a new import declaration, but since
      // this code is running at build time, we can simplify things by throwing
      // here, because we expect invariant and InvariantError to be imported
      // from the utilities/globals subpackage.
      throw new Error(`Missing import from "${
        posix.relative(
          posix.dirname(relativeFilePath),
          "utilities/globals",
        )
       } in ${relativeFilePath}`);
    }
  }

  return reprint(ast);
}

function isIdWithName(node: Node | null | undefined, ...names: string[]) {
  return node && n.Identifier.check(node) &&
    names.some(name => name === node.name);
}

function isCallWithLength(
  node: CallExpression | NewExpression,
  name: string,
  length: number,
) {
  return isIdWithName(node.callee, name) &&
    node.arguments.length > length;
}

function isDEVConditional(node: Node) {
  return n.ConditionalExpression.check(node) &&
    isDEVExpr(node.test);
}

function isDEVLogicalAnd(node: Node) {
  return n.LogicalExpression.check(node) &&
    node.operator === "&&" &&
    isDEVExpr(node.left);
}

function makeDEVExpr() {
  // typeof __DEV__ !== "undefined" ? Boolean(__DEV__) : typeof process !== "undefined" && process.env.NODE_ENV !== "production"
  return b.conditionalExpression(
    b.binaryExpression(
      "!==",
      b.unaryExpression("typeof", b.identifier("__DEV__")),
      b.stringLiteral("undefined")
      ),
    b.callExpression(
      b.identifier("Boolean"),
      [b.identifier("__DEV__")],
    ),
    b.logicalExpression(
      "&&",
      b.binaryExpression(
        "!==",
        b.unaryExpression("typeof", b.identifier("process")),
        b.stringLiteral("undefined")
      ),
      b.binaryExpression(
        "!==",
        b.memberExpression(b.memberExpression(
          b.identifier("process"),
          b.identifier("env")), b.identifier("NODE_ENV")
        ),
        b.stringLiteral("production")
      ),
    )
  );
}

function isDEVExpr(node: Node) {
  return isIdWithName(node, "__DEV__");
}
