name: Clean up Prettier, Size-limit, and Api-Extractor

on:
  pull_request:
  pull_request_review:
    types: [submitted]

jobs:
  add_cleanup_label:
    if: |
      github.repository == 'apollographql/apollo-client' &&
      github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: add label
        uses: actions-ecosystem/action-add-labels@v1
        with:
          labels: auto-cleanup

  cleanup:
    if: |
      github.repository == 'apollographql/apollo-client' &&
      contains(github.event.pull_request.labels.*.name, 'auto-cleanup')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1

      - name: Run build
        run: npm run build

      - name: Run Api-Extractor
        run: npm run extract-api
        env:
          CI: false

      - name: Run prettier
        run: npm run format

      - name: Update size-limit
        run: npm run update-size-limits

      # commit & push
      # if there is a "trigger this action" comment in the PR, remove it

      # - name: Create comment
      #   if: ${{ steps.added-files.outputs.changesets != '' }}
      #   uses: peter-evans/create-or-update-comment@v3.1.0
      #   with:
      #     issue-number: ${{ github.event.issue.number }}
      #     body: |
      #       A new release has been made for this PR. You can install it with `npm i @apollo/client@${{ steps.get-version.outputs.version }}`.
