name: Clean up Prettier, Size-limit, and Api-Extractor

on:
  pull_request:
  pull_request_review:
    types: [submitted, edited]

permissions: {}

jobs:
  add_cleanup_label:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-a-workflow-when-a-pull-request-is-approved
    permissions:
      contents: read
      pull-requests: write
    if: |
      github.repository == 'apollographql/apollo-client' &&
      github.event.review.state == 'APPROVED' &&
      github.event.review.author_association == 'MEMBER' &&
      contains(github.event.pull_request.labels.*.name, 'auto-cleanup') == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false
      - name: add label
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          script: |
            const script = (await import('${{ github.workspace }}/.github/workflows/cleanup-checks.mjs')).setup({context,core,github,exec,glob,io})
            await script.add_cleanup_label()

  cleanup:
    permissions:
      contents: write
    if: |
      github.repository == 'apollographql/apollo-client' &&
      contains(github.event.pull_request.labels.*.name, 'auto-cleanup')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ">=23.6.0"

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb #v1

      - name: Run Api-Extractor
        run: npm run extract-api
        env:
          CI: "false"

      - name: Run prettier
        run: npm run format

      - name: Run build
        run: npm run build

      - name: Update size-limit
        run: npm run update-size-limits

      - name: Commit changes back
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: "Clean up Prettier, Size-limit, and Api-Extractor"
          push_options: ""
          skip_dirty_check: false
