name: Unit tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - name: Install dependencies
        run: npm install
      - name: run unit tests
        run: npm run test
        env:
          NODE_OPTIONS: -r dd-trace/ci/init
          DD_API_KEY: ${{ secrets.DD_API_KEY }}
          DD_CIVISIBILITY_AGENTLESS_ENABLED: 1
          DD_APP_KEY: ${{ secrets.DD_APP_KEY }}
          DD_TRACE_DEBUG: 1
          DD_TRACE_LOG_LEVEL: error
          DD_CIVISIBILITY_GIT_UPLOAD_ENABLED: 1
          DD_ENV: ci
          DD_SERVICE: apollo-client-tests
          # DD_CIVISIBILITY_ITR_ENABLED: 1

