name: Generate Documentation Model

on:
  push:

permissions:
  contents: read

jobs:
  docmodel:
    name: Generate Documentation Model
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ">=23.6.0"

      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # v1

      - name: Generate documentation model
        run: npm run docmodel

      - name: Upload documentation model artifact
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: client-api-documentation
          path: docs/public/client.api.json
          retention-days: 30
