name: Deploy docs to production

on:
  push:
    branches:
      - main
      - version-2.6
    paths:
      - docs/**

permissions:
  contents: read

jobs:
  publish:
    uses: apollographql/docs/.github/workflows/publish.yml@main
    secrets:
      NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
      NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
