name: Look for dead code and unused dependencies

on: push

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Ubuntu/Node v20
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: actions/setup-node@v6
      - name: Install dependencies (with cache)
        uses: bahmutov/npm-install@v1
      - name: Run knip
        run: npm run knip
