name: Lint and Filesize Check

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - "release-*"
    paths-ignore:
      - "docs/**"
      - "**/*.md"
  pull_request:
    paths-ignore:
      - "docs/**"
      - "**/*.md"

jobs:
  lint_and_filesize_check:
    if: github.repository == 'apollographql/apollo-client'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies with cache
        uses: bahmutov/npm-install@v1

      - name: Run CI Precheck
        run: npm run ci:precheck

      - name: Run npm version
        run: npm version

      - name: Run ESLint
        run: npm run lint

      - name: Run bundlesize check
        run: npm run bundlesize
