# a GitHub Action that once a day runs all tests from `main` and `release-*` branches
# with the latest `canary` and `experimental` release of `react` and `react-dom`
name: Scheduled React Canary Test
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      branches:
        description: "Branches to test"
        required: true
        default: '["main", "release-3.13", "release-4.0"]'
      tags:
        description: "React and React-DOM versions"
        required: true
        default: '["canary", "experimental"]'
permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        tag: ${{ fromJson(github.event_name == 'workflow_dispatch' && inputs.tags || '["canary", "experimental"]') }}
        branch: ${{ fromJson(github.event_name == 'workflow_dispatch' && inputs.branches || '["main", "release-3.13", "release-4.0"]') }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ matrix.branch }}
          persist-credentials: false
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: ">=23.6.0"
      - uses: bahmutov/npm-install@20216767ca67f0f7b4d095dc5859c5700a6581cb # v1
      - run: |
          npm install react@${MATRIX_TAG} react-dom@${MATRIX_TAG}
        env:
          MATRIX_TAG: ${{ matrix.tag }}
      # tests can be flaky, this runs only once a day and we want to minimize false negatives - retry up to three times
      - run: |
          node -e 'console.log("\n\nReact %s, React-DOM %s\n\n", require("react").version, require("react-dom").version)'
          parallel --line-buffer -j 1 --retries 3 'npm test -- --logHeapUsage --selectProjects ' ::: 'ReactDOM 19'
