name: "size"
on:
  pull_request:
    branches:
      - main
      - release-*
      - pr/*
jobs:
  size:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7
        with:
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: "24.x"
      - run: npm ci
      - name: Run size-limit
        uses: andresz1/size-limit-action@e7493a72a44b113341c0cf6186ab49c17c4b65c1 # v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
